package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class CkCheck {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.EP_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CT_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CT_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.BG_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String BG_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal CK_NNUM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SGROUP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SGROUP;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_DTIME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_DTIME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SRESULT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SRESULT;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String CK_SDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal CK_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal CK_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal CK_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal CK_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal CK_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_TDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_TDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_TDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_TDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_TDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.CK_CHECK.CK_TDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date CK_TDEF6;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SID
     *
     * @return the value of CG.CK_CHECK.CK_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SID() {
        return CK_SID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SID
     *
     * @param CK_SID the value for CG.CK_CHECK.CK_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SID(String CK_SID) {
        this.CK_SID = CK_SID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.EP_SID
     *
     * @return the value of CG.CK_CHECK.EP_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SID() {
        return EP_SID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.EP_SID
     *
     * @param EP_SID the value for CG.CK_CHECK.EP_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SID(String EP_SID) {
        this.EP_SID = EP_SID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CT_SNO
     *
     * @return the value of CG.CK_CHECK.CT_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCT_SNO() {
        return CT_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CT_SNO
     *
     * @param CT_SNO the value for CG.CK_CHECK.CT_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCT_SNO(String CT_SNO) {
        this.CT_SNO = CT_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.BG_SNO
     *
     * @return the value of CG.CK_CHECK.BG_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getBG_SNO() {
        return BG_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.BG_SNO
     *
     * @param BG_SNO the value for CG.CK_CHECK.BG_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setBG_SNO(String BG_SNO) {
        this.BG_SNO = BG_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_NNUM
     *
     * @return the value of CG.CK_CHECK.CK_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getCK_NNUM() {
        return CK_NNUM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_NNUM
     *
     * @param CK_NNUM the value for CG.CK_CHECK.CK_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_NNUM(BigDecimal CK_NNUM) {
        this.CK_NNUM = CK_NNUM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SGROUP
     *
     * @return the value of CG.CK_CHECK.CK_SGROUP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SGROUP() {
        return CK_SGROUP;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SGROUP
     *
     * @param CK_SGROUP the value for CG.CK_CHECK.CK_SGROUP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SGROUP(String CK_SGROUP) {
        this.CK_SGROUP = CK_SGROUP;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_DTIME
     *
     * @return the value of CG.CK_CHECK.CK_DTIME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_DTIME() {
        return CK_DTIME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_DTIME
     *
     * @param CK_DTIME the value for CG.CK_CHECK.CK_DTIME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_DTIME(Date CK_DTIME) {
        this.CK_DTIME = CK_DTIME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SRESULT
     *
     * @return the value of CG.CK_CHECK.CK_SRESULT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SRESULT() {
        return CK_SRESULT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SRESULT
     *
     * @param CK_SRESULT the value for CG.CK_CHECK.CK_SRESULT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SRESULT(String CK_SRESULT) {
        this.CK_SRESULT = CK_SRESULT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SISDEL
     *
     * @return the value of CG.CK_CHECK.CK_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SISDEL() {
        return CK_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SISDEL
     *
     * @param CK_SISDEL the value for CG.CK_CHECK.CK_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SISDEL(String CK_SISDEL) {
        this.CK_SISDEL = CK_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SISVALID
     *
     * @return the value of CG.CK_CHECK.CK_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SISVALID() {
        return CK_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SISVALID
     *
     * @param CK_SISVALID the value for CG.CK_CHECK.CK_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SISVALID(String CK_SISVALID) {
        this.CK_SISVALID = CK_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SREPLYBY
     *
     * @return the value of CG.CK_CHECK.CK_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SREPLYBY() {
        return CK_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SREPLYBY
     *
     * @param CK_SREPLYBY the value for CG.CK_CHECK.CK_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SREPLYBY(String CK_SREPLYBY) {
        this.CK_SREPLYBY = CK_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SREPLYDATE
     *
     * @return the value of CG.CK_CHECK.CK_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_SREPLYDATE() {
        return CK_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SREPLYDATE
     *
     * @param CK_SREPLYDATE the value for CG.CK_CHECK.CK_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SREPLYDATE(Date CK_SREPLYDATE) {
        this.CK_SREPLYDATE = CK_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SALTERBY
     *
     * @return the value of CG.CK_CHECK.CK_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SALTERBY() {
        return CK_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SALTERBY
     *
     * @param CK_SALTERBY the value for CG.CK_CHECK.CK_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SALTERBY(String CK_SALTERBY) {
        this.CK_SALTERBY = CK_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SALTERDATE
     *
     * @return the value of CG.CK_CHECK.CK_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_SALTERDATE() {
        return CK_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SALTERDATE
     *
     * @param CK_SALTERDATE the value for CG.CK_CHECK.CK_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SALTERDATE(Date CK_SALTERDATE) {
        this.CK_SALTERDATE = CK_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF1
     *
     * @return the value of CG.CK_CHECK.CK_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF1() {
        return CK_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF1
     *
     * @param CK_SDEF1 the value for CG.CK_CHECK.CK_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF1(String CK_SDEF1) {
        this.CK_SDEF1 = CK_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF2
     *
     * @return the value of CG.CK_CHECK.CK_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF2() {
        return CK_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF2
     *
     * @param CK_SDEF2 the value for CG.CK_CHECK.CK_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF2(String CK_SDEF2) {
        this.CK_SDEF2 = CK_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF3
     *
     * @return the value of CG.CK_CHECK.CK_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF3() {
        return CK_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF3
     *
     * @param CK_SDEF3 the value for CG.CK_CHECK.CK_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF3(String CK_SDEF3) {
        this.CK_SDEF3 = CK_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF4
     *
     * @return the value of CG.CK_CHECK.CK_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF4() {
        return CK_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF4
     *
     * @param CK_SDEF4 the value for CG.CK_CHECK.CK_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF4(String CK_SDEF4) {
        this.CK_SDEF4 = CK_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF5
     *
     * @return the value of CG.CK_CHECK.CK_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF5() {
        return CK_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF5
     *
     * @param CK_SDEF5 the value for CG.CK_CHECK.CK_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF5(String CK_SDEF5) {
        this.CK_SDEF5 = CK_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF6
     *
     * @return the value of CG.CK_CHECK.CK_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF6() {
        return CK_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF6
     *
     * @param CK_SDEF6 the value for CG.CK_CHECK.CK_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF6(String CK_SDEF6) {
        this.CK_SDEF6 = CK_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF7
     *
     * @return the value of CG.CK_CHECK.CK_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF7() {
        return CK_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF7
     *
     * @param CK_SDEF7 the value for CG.CK_CHECK.CK_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF7(String CK_SDEF7) {
        this.CK_SDEF7 = CK_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF8
     *
     * @return the value of CG.CK_CHECK.CK_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF8() {
        return CK_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF8
     *
     * @param CK_SDEF8 the value for CG.CK_CHECK.CK_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF8(String CK_SDEF8) {
        this.CK_SDEF8 = CK_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF9
     *
     * @return the value of CG.CK_CHECK.CK_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF9() {
        return CK_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF9
     *
     * @param CK_SDEF9 the value for CG.CK_CHECK.CK_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF9(String CK_SDEF9) {
        this.CK_SDEF9 = CK_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF10
     *
     * @return the value of CG.CK_CHECK.CK_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF10() {
        return CK_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF10
     *
     * @param CK_SDEF10 the value for CG.CK_CHECK.CK_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF10(String CK_SDEF10) {
        this.CK_SDEF10 = CK_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF11
     *
     * @return the value of CG.CK_CHECK.CK_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF11() {
        return CK_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF11
     *
     * @param CK_SDEF11 the value for CG.CK_CHECK.CK_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF11(String CK_SDEF11) {
        this.CK_SDEF11 = CK_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF12
     *
     * @return the value of CG.CK_CHECK.CK_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF12() {
        return CK_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF12
     *
     * @param CK_SDEF12 the value for CG.CK_CHECK.CK_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF12(String CK_SDEF12) {
        this.CK_SDEF12 = CK_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF13
     *
     * @return the value of CG.CK_CHECK.CK_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF13() {
        return CK_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF13
     *
     * @param CK_SDEF13 the value for CG.CK_CHECK.CK_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF13(String CK_SDEF13) {
        this.CK_SDEF13 = CK_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF14
     *
     * @return the value of CG.CK_CHECK.CK_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF14() {
        return CK_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF14
     *
     * @param CK_SDEF14 the value for CG.CK_CHECK.CK_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF14(String CK_SDEF14) {
        this.CK_SDEF14 = CK_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF15
     *
     * @return the value of CG.CK_CHECK.CK_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF15() {
        return CK_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF15
     *
     * @param CK_SDEF15 the value for CG.CK_CHECK.CK_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF15(String CK_SDEF15) {
        this.CK_SDEF15 = CK_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF16
     *
     * @return the value of CG.CK_CHECK.CK_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF16() {
        return CK_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF16
     *
     * @param CK_SDEF16 the value for CG.CK_CHECK.CK_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF16(String CK_SDEF16) {
        this.CK_SDEF16 = CK_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF17
     *
     * @return the value of CG.CK_CHECK.CK_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF17() {
        return CK_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF17
     *
     * @param CK_SDEF17 the value for CG.CK_CHECK.CK_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF17(String CK_SDEF17) {
        this.CK_SDEF17 = CK_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF18
     *
     * @return the value of CG.CK_CHECK.CK_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF18() {
        return CK_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF18
     *
     * @param CK_SDEF18 the value for CG.CK_CHECK.CK_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF18(String CK_SDEF18) {
        this.CK_SDEF18 = CK_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF19
     *
     * @return the value of CG.CK_CHECK.CK_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF19() {
        return CK_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF19
     *
     * @param CK_SDEF19 the value for CG.CK_CHECK.CK_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF19(String CK_SDEF19) {
        this.CK_SDEF19 = CK_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_SDEF20
     *
     * @return the value of CG.CK_CHECK.CK_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getCK_SDEF20() {
        return CK_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_SDEF20
     *
     * @param CK_SDEF20 the value for CG.CK_CHECK.CK_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_SDEF20(String CK_SDEF20) {
        this.CK_SDEF20 = CK_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_NDEF1
     *
     * @return the value of CG.CK_CHECK.CK_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getCK_NDEF1() {
        return CK_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_NDEF1
     *
     * @param CK_NDEF1 the value for CG.CK_CHECK.CK_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_NDEF1(BigDecimal CK_NDEF1) {
        this.CK_NDEF1 = CK_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_NDEF2
     *
     * @return the value of CG.CK_CHECK.CK_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getCK_NDEF2() {
        return CK_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_NDEF2
     *
     * @param CK_NDEF2 the value for CG.CK_CHECK.CK_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_NDEF2(BigDecimal CK_NDEF2) {
        this.CK_NDEF2 = CK_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_NDEF3
     *
     * @return the value of CG.CK_CHECK.CK_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getCK_NDEF3() {
        return CK_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_NDEF3
     *
     * @param CK_NDEF3 the value for CG.CK_CHECK.CK_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_NDEF3(BigDecimal CK_NDEF3) {
        this.CK_NDEF3 = CK_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_NDEF4
     *
     * @return the value of CG.CK_CHECK.CK_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getCK_NDEF4() {
        return CK_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_NDEF4
     *
     * @param CK_NDEF4 the value for CG.CK_CHECK.CK_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_NDEF4(BigDecimal CK_NDEF4) {
        this.CK_NDEF4 = CK_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_NDEF5
     *
     * @return the value of CG.CK_CHECK.CK_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getCK_NDEF5() {
        return CK_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_NDEF5
     *
     * @param CK_NDEF5 the value for CG.CK_CHECK.CK_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_NDEF5(BigDecimal CK_NDEF5) {
        this.CK_NDEF5 = CK_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_TDEF1
     *
     * @return the value of CG.CK_CHECK.CK_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_TDEF1() {
        return CK_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_TDEF1
     *
     * @param CK_TDEF1 the value for CG.CK_CHECK.CK_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_TDEF1(Date CK_TDEF1) {
        this.CK_TDEF1 = CK_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_TDEF2
     *
     * @return the value of CG.CK_CHECK.CK_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_TDEF2() {
        return CK_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_TDEF2
     *
     * @param CK_TDEF2 the value for CG.CK_CHECK.CK_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_TDEF2(Date CK_TDEF2) {
        this.CK_TDEF2 = CK_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_TDEF3
     *
     * @return the value of CG.CK_CHECK.CK_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_TDEF3() {
        return CK_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_TDEF3
     *
     * @param CK_TDEF3 the value for CG.CK_CHECK.CK_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_TDEF3(Date CK_TDEF3) {
        this.CK_TDEF3 = CK_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_TDEF4
     *
     * @return the value of CG.CK_CHECK.CK_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_TDEF4() {
        return CK_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_TDEF4
     *
     * @param CK_TDEF4 the value for CG.CK_CHECK.CK_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_TDEF4(Date CK_TDEF4) {
        this.CK_TDEF4 = CK_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_TDEF5
     *
     * @return the value of CG.CK_CHECK.CK_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_TDEF5() {
        return CK_TDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_TDEF5
     *
     * @param CK_TDEF5 the value for CG.CK_CHECK.CK_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_TDEF5(Date CK_TDEF5) {
        this.CK_TDEF5 = CK_TDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.CK_CHECK.CK_TDEF6
     *
     * @return the value of CG.CK_CHECK.CK_TDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getCK_TDEF6() {
        return CK_TDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.CK_CHECK.CK_TDEF6
     *
     * @param CK_TDEF6 the value for CG.CK_CHECK.CK_TDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setCK_TDEF6(Date CK_TDEF6) {
        this.CK_TDEF6 = CK_TDEF6;
    }
}