package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class EpSetting {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SPURTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SPURTYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NWORK;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SPAGE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SPAGE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SPERSONTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SPERSONTYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SREMARK;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String SET_SDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal SET_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_TDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_TDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_TDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_TDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_SETTING.SET_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date SET_TDEF5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NID
     *
     * @return the value of CG.EP_SETTING.SET_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NID() {
        return SET_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NID
     *
     * @param SET_NID the value for CG.EP_SETTING.SET_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NID(BigDecimal SET_NID) {
        this.SET_NID = SET_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SPURTYPE
     *
     * @return the value of CG.EP_SETTING.SET_SPURTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SPURTYPE() {
        return SET_SPURTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SPURTYPE
     *
     * @param SET_SPURTYPE the value for CG.EP_SETTING.SET_SPURTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SPURTYPE(String SET_SPURTYPE) {
        this.SET_SPURTYPE = SET_SPURTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NNO
     *
     * @return the value of CG.EP_SETTING.SET_NNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NNO() {
        return SET_NNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NNO
     *
     * @param SET_NNO the value for CG.EP_SETTING.SET_NNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NNO(BigDecimal SET_NNO) {
        this.SET_NNO = SET_NNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SNAME
     *
     * @return the value of CG.EP_SETTING.SET_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SNAME() {
        return SET_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SNAME
     *
     * @param SET_SNAME the value for CG.EP_SETTING.SET_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SNAME(String SET_SNAME) {
        this.SET_SNAME = SET_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NWORK
     *
     * @return the value of CG.EP_SETTING.SET_NWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NWORK() {
        return SET_NWORK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NWORK
     *
     * @param SET_NWORK the value for CG.EP_SETTING.SET_NWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NWORK(BigDecimal SET_NWORK) {
        this.SET_NWORK = SET_NWORK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SPAGE
     *
     * @return the value of CG.EP_SETTING.SET_SPAGE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SPAGE() {
        return SET_SPAGE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SPAGE
     *
     * @param SET_SPAGE the value for CG.EP_SETTING.SET_SPAGE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SPAGE(String SET_SPAGE) {
        this.SET_SPAGE = SET_SPAGE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SPERSONTYPE
     *
     * @return the value of CG.EP_SETTING.SET_SPERSONTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SPERSONTYPE() {
        return SET_SPERSONTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SPERSONTYPE
     *
     * @param SET_SPERSONTYPE the value for CG.EP_SETTING.SET_SPERSONTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SPERSONTYPE(String SET_SPERSONTYPE) {
        this.SET_SPERSONTYPE = SET_SPERSONTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SREMARK
     *
     * @return the value of CG.EP_SETTING.SET_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SREMARK() {
        return SET_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SREMARK
     *
     * @param SET_SREMARK the value for CG.EP_SETTING.SET_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SREMARK(String SET_SREMARK) {
        this.SET_SREMARK = SET_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SISDEL
     *
     * @return the value of CG.EP_SETTING.SET_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SISDEL() {
        return SET_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SISDEL
     *
     * @param SET_SISDEL the value for CG.EP_SETTING.SET_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SISDEL(String SET_SISDEL) {
        this.SET_SISDEL = SET_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SISVALID
     *
     * @return the value of CG.EP_SETTING.SET_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SISVALID() {
        return SET_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SISVALID
     *
     * @param SET_SISVALID the value for CG.EP_SETTING.SET_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SISVALID(String SET_SISVALID) {
        this.SET_SISVALID = SET_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SREPLYBY
     *
     * @return the value of CG.EP_SETTING.SET_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SREPLYBY() {
        return SET_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SREPLYBY
     *
     * @param SET_SREPLYBY the value for CG.EP_SETTING.SET_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SREPLYBY(String SET_SREPLYBY) {
        this.SET_SREPLYBY = SET_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SREPLYDATE
     *
     * @return the value of CG.EP_SETTING.SET_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_SREPLYDATE() {
        return SET_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SREPLYDATE
     *
     * @param SET_SREPLYDATE the value for CG.EP_SETTING.SET_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SREPLYDATE(Date SET_SREPLYDATE) {
        this.SET_SREPLYDATE = SET_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SALTERBY
     *
     * @return the value of CG.EP_SETTING.SET_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SALTERBY() {
        return SET_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SALTERBY
     *
     * @param SET_SALTERBY the value for CG.EP_SETTING.SET_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SALTERBY(String SET_SALTERBY) {
        this.SET_SALTERBY = SET_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SALTERDATE
     *
     * @return the value of CG.EP_SETTING.SET_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_SALTERDATE() {
        return SET_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SALTERDATE
     *
     * @param SET_SALTERDATE the value for CG.EP_SETTING.SET_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SALTERDATE(Date SET_SALTERDATE) {
        this.SET_SALTERDATE = SET_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF1
     *
     * @return the value of CG.EP_SETTING.SET_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF1() {
        return SET_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF1
     *
     * @param SET_SDEF1 the value for CG.EP_SETTING.SET_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF1(String SET_SDEF1) {
        this.SET_SDEF1 = SET_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF2
     *
     * @return the value of CG.EP_SETTING.SET_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF2() {
        return SET_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF2
     *
     * @param SET_SDEF2 the value for CG.EP_SETTING.SET_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF2(String SET_SDEF2) {
        this.SET_SDEF2 = SET_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF3
     *
     * @return the value of CG.EP_SETTING.SET_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF3() {
        return SET_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF3
     *
     * @param SET_SDEF3 the value for CG.EP_SETTING.SET_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF3(String SET_SDEF3) {
        this.SET_SDEF3 = SET_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF4
     *
     * @return the value of CG.EP_SETTING.SET_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF4() {
        return SET_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF4
     *
     * @param SET_SDEF4 the value for CG.EP_SETTING.SET_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF4(String SET_SDEF4) {
        this.SET_SDEF4 = SET_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF5
     *
     * @return the value of CG.EP_SETTING.SET_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF5() {
        return SET_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF5
     *
     * @param SET_SDEF5 the value for CG.EP_SETTING.SET_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF5(String SET_SDEF5) {
        this.SET_SDEF5 = SET_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF6
     *
     * @return the value of CG.EP_SETTING.SET_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF6() {
        return SET_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF6
     *
     * @param SET_SDEF6 the value for CG.EP_SETTING.SET_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF6(String SET_SDEF6) {
        this.SET_SDEF6 = SET_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF7
     *
     * @return the value of CG.EP_SETTING.SET_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF7() {
        return SET_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF7
     *
     * @param SET_SDEF7 the value for CG.EP_SETTING.SET_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF7(String SET_SDEF7) {
        this.SET_SDEF7 = SET_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF8
     *
     * @return the value of CG.EP_SETTING.SET_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF8() {
        return SET_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF8
     *
     * @param SET_SDEF8 the value for CG.EP_SETTING.SET_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF8(String SET_SDEF8) {
        this.SET_SDEF8 = SET_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF9
     *
     * @return the value of CG.EP_SETTING.SET_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF9() {
        return SET_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF9
     *
     * @param SET_SDEF9 the value for CG.EP_SETTING.SET_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF9(String SET_SDEF9) {
        this.SET_SDEF9 = SET_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF10
     *
     * @return the value of CG.EP_SETTING.SET_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF10() {
        return SET_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF10
     *
     * @param SET_SDEF10 the value for CG.EP_SETTING.SET_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF10(String SET_SDEF10) {
        this.SET_SDEF10 = SET_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF11
     *
     * @return the value of CG.EP_SETTING.SET_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF11() {
        return SET_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF11
     *
     * @param SET_SDEF11 the value for CG.EP_SETTING.SET_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF11(String SET_SDEF11) {
        this.SET_SDEF11 = SET_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF12
     *
     * @return the value of CG.EP_SETTING.SET_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF12() {
        return SET_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF12
     *
     * @param SET_SDEF12 the value for CG.EP_SETTING.SET_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF12(String SET_SDEF12) {
        this.SET_SDEF12 = SET_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF13
     *
     * @return the value of CG.EP_SETTING.SET_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF13() {
        return SET_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF13
     *
     * @param SET_SDEF13 the value for CG.EP_SETTING.SET_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF13(String SET_SDEF13) {
        this.SET_SDEF13 = SET_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF14
     *
     * @return the value of CG.EP_SETTING.SET_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF14() {
        return SET_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF14
     *
     * @param SET_SDEF14 the value for CG.EP_SETTING.SET_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF14(String SET_SDEF14) {
        this.SET_SDEF14 = SET_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF15
     *
     * @return the value of CG.EP_SETTING.SET_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF15() {
        return SET_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF15
     *
     * @param SET_SDEF15 the value for CG.EP_SETTING.SET_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF15(String SET_SDEF15) {
        this.SET_SDEF15 = SET_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF16
     *
     * @return the value of CG.EP_SETTING.SET_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF16() {
        return SET_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF16
     *
     * @param SET_SDEF16 the value for CG.EP_SETTING.SET_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF16(String SET_SDEF16) {
        this.SET_SDEF16 = SET_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF17
     *
     * @return the value of CG.EP_SETTING.SET_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF17() {
        return SET_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF17
     *
     * @param SET_SDEF17 the value for CG.EP_SETTING.SET_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF17(String SET_SDEF17) {
        this.SET_SDEF17 = SET_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF18
     *
     * @return the value of CG.EP_SETTING.SET_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF18() {
        return SET_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF18
     *
     * @param SET_SDEF18 the value for CG.EP_SETTING.SET_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF18(String SET_SDEF18) {
        this.SET_SDEF18 = SET_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF19
     *
     * @return the value of CG.EP_SETTING.SET_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF19() {
        return SET_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF19
     *
     * @param SET_SDEF19 the value for CG.EP_SETTING.SET_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF19(String SET_SDEF19) {
        this.SET_SDEF19 = SET_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_SDEF20
     *
     * @return the value of CG.EP_SETTING.SET_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getSET_SDEF20() {
        return SET_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_SDEF20
     *
     * @param SET_SDEF20 the value for CG.EP_SETTING.SET_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_SDEF20(String SET_SDEF20) {
        this.SET_SDEF20 = SET_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NDEF1
     *
     * @return the value of CG.EP_SETTING.SET_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NDEF1() {
        return SET_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NDEF1
     *
     * @param SET_NDEF1 the value for CG.EP_SETTING.SET_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NDEF1(BigDecimal SET_NDEF1) {
        this.SET_NDEF1 = SET_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NDEF2
     *
     * @return the value of CG.EP_SETTING.SET_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NDEF2() {
        return SET_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NDEF2
     *
     * @param SET_NDEF2 the value for CG.EP_SETTING.SET_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NDEF2(BigDecimal SET_NDEF2) {
        this.SET_NDEF2 = SET_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NDEF3
     *
     * @return the value of CG.EP_SETTING.SET_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NDEF3() {
        return SET_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NDEF3
     *
     * @param SET_NDEF3 the value for CG.EP_SETTING.SET_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NDEF3(BigDecimal SET_NDEF3) {
        this.SET_NDEF3 = SET_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NDEF4
     *
     * @return the value of CG.EP_SETTING.SET_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NDEF4() {
        return SET_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NDEF4
     *
     * @param SET_NDEF4 the value for CG.EP_SETTING.SET_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NDEF4(BigDecimal SET_NDEF4) {
        this.SET_NDEF4 = SET_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_NDEF5
     *
     * @return the value of CG.EP_SETTING.SET_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getSET_NDEF5() {
        return SET_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_NDEF5
     *
     * @param SET_NDEF5 the value for CG.EP_SETTING.SET_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_NDEF5(BigDecimal SET_NDEF5) {
        this.SET_NDEF5 = SET_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_TDEF1
     *
     * @return the value of CG.EP_SETTING.SET_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_TDEF1() {
        return SET_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_TDEF1
     *
     * @param SET_TDEF1 the value for CG.EP_SETTING.SET_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_TDEF1(Date SET_TDEF1) {
        this.SET_TDEF1 = SET_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_TDEF2
     *
     * @return the value of CG.EP_SETTING.SET_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_TDEF2() {
        return SET_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_TDEF2
     *
     * @param SET_TDEF2 the value for CG.EP_SETTING.SET_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_TDEF2(Date SET_TDEF2) {
        this.SET_TDEF2 = SET_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_TDEF3
     *
     * @return the value of CG.EP_SETTING.SET_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_TDEF3() {
        return SET_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_TDEF3
     *
     * @param SET_TDEF3 the value for CG.EP_SETTING.SET_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_TDEF3(Date SET_TDEF3) {
        this.SET_TDEF3 = SET_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_TDEF4
     *
     * @return the value of CG.EP_SETTING.SET_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_TDEF4() {
        return SET_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_TDEF4
     *
     * @param SET_TDEF4 the value for CG.EP_SETTING.SET_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_TDEF4(Date SET_TDEF4) {
        this.SET_TDEF4 = SET_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_SETTING.SET_TDEF5
     *
     * @return the value of CG.EP_SETTING.SET_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getSET_TDEF5() {
        return SET_TDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_SETTING.SET_TDEF5
     *
     * @param SET_TDEF5 the value for CG.EP_SETTING.SET_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setSET_TDEF5(Date SET_TDEF5) {
        this.SET_TDEF5 = SET_TDEF5;
    }
}