package com.rc.project.form;

import java.math.BigDecimal;
import java.util.Date;

public class EpFormworkForm {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal FORM_NID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_STYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_STYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SURL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SURL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SREMARK;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String FORM_SDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal FORM_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal FORM_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal FORM_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal FORM_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal FORM_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_TDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_TDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_TDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_TDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_FORMWORK.FORM_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date FORM_TDEF5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_NID
     *
     * @return the value of CG.EP_FORMWORK.FORM_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getFORM_NID() {
        return FORM_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_NID
     *
     * @param FORM_NID the value for CG.EP_FORMWORK.FORM_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_NID(BigDecimal FORM_NID) {
        this.FORM_NID = FORM_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SNAME
     *
     * @return the value of CG.EP_FORMWORK.FORM_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SNAME() {
        return FORM_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SNAME
     *
     * @param FORM_SNAME the value for CG.EP_FORMWORK.FORM_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SNAME(String FORM_SNAME) {
        this.FORM_SNAME = FORM_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_STYPE
     *
     * @return the value of CG.EP_FORMWORK.FORM_STYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_STYPE() {
        return FORM_STYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_STYPE
     *
     * @param FORM_STYPE the value for CG.EP_FORMWORK.FORM_STYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_STYPE(String FORM_STYPE) {
        this.FORM_STYPE = FORM_STYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SURL
     *
     * @return the value of CG.EP_FORMWORK.FORM_SURL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SURL() {
        return FORM_SURL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SURL
     *
     * @param FORM_SURL the value for CG.EP_FORMWORK.FORM_SURL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SURL(String FORM_SURL) {
        this.FORM_SURL = FORM_SURL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SREMARK
     *
     * @return the value of CG.EP_FORMWORK.FORM_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SREMARK() {
        return FORM_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SREMARK
     *
     * @param FORM_SREMARK the value for CG.EP_FORMWORK.FORM_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SREMARK(String FORM_SREMARK) {
        this.FORM_SREMARK = FORM_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SISDEL
     *
     * @return the value of CG.EP_FORMWORK.FORM_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SISDEL() {
        return FORM_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SISDEL
     *
     * @param FORM_SISDEL the value for CG.EP_FORMWORK.FORM_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SISDEL(String FORM_SISDEL) {
        this.FORM_SISDEL = FORM_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SISVALID
     *
     * @return the value of CG.EP_FORMWORK.FORM_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SISVALID() {
        return FORM_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SISVALID
     *
     * @param FORM_SISVALID the value for CG.EP_FORMWORK.FORM_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SISVALID(String FORM_SISVALID) {
        this.FORM_SISVALID = FORM_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SREPLYBY
     *
     * @return the value of CG.EP_FORMWORK.FORM_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SREPLYBY() {
        return FORM_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SREPLYBY
     *
     * @param FORM_SREPLYBY the value for CG.EP_FORMWORK.FORM_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SREPLYBY(String FORM_SREPLYBY) {
        this.FORM_SREPLYBY = FORM_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SREPLYDATE
     *
     * @return the value of CG.EP_FORMWORK.FORM_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_SREPLYDATE() {
        return FORM_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SREPLYDATE
     *
     * @param FORM_SREPLYDATE the value for CG.EP_FORMWORK.FORM_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SREPLYDATE(Date FORM_SREPLYDATE) {
        this.FORM_SREPLYDATE = FORM_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SALTERBY
     *
     * @return the value of CG.EP_FORMWORK.FORM_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SALTERBY() {
        return FORM_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SALTERBY
     *
     * @param FORM_SALTERBY the value for CG.EP_FORMWORK.FORM_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SALTERBY(String FORM_SALTERBY) {
        this.FORM_SALTERBY = FORM_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SALTERDATE
     *
     * @return the value of CG.EP_FORMWORK.FORM_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_SALTERDATE() {
        return FORM_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SALTERDATE
     *
     * @param FORM_SALTERDATE the value for CG.EP_FORMWORK.FORM_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SALTERDATE(Date FORM_SALTERDATE) {
        this.FORM_SALTERDATE = FORM_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF1
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF1() {
        return FORM_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF1
     *
     * @param FORM_SDEF1 the value for CG.EP_FORMWORK.FORM_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF1(String FORM_SDEF1) {
        this.FORM_SDEF1 = FORM_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF2
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF2() {
        return FORM_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF2
     *
     * @param FORM_SDEF2 the value for CG.EP_FORMWORK.FORM_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF2(String FORM_SDEF2) {
        this.FORM_SDEF2 = FORM_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF3
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF3() {
        return FORM_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF3
     *
     * @param FORM_SDEF3 the value for CG.EP_FORMWORK.FORM_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF3(String FORM_SDEF3) {
        this.FORM_SDEF3 = FORM_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF4
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF4() {
        return FORM_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF4
     *
     * @param FORM_SDEF4 the value for CG.EP_FORMWORK.FORM_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF4(String FORM_SDEF4) {
        this.FORM_SDEF4 = FORM_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF5
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF5() {
        return FORM_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF5
     *
     * @param FORM_SDEF5 the value for CG.EP_FORMWORK.FORM_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF5(String FORM_SDEF5) {
        this.FORM_SDEF5 = FORM_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF6
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF6() {
        return FORM_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF6
     *
     * @param FORM_SDEF6 the value for CG.EP_FORMWORK.FORM_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF6(String FORM_SDEF6) {
        this.FORM_SDEF6 = FORM_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF7
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF7() {
        return FORM_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF7
     *
     * @param FORM_SDEF7 the value for CG.EP_FORMWORK.FORM_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF7(String FORM_SDEF7) {
        this.FORM_SDEF7 = FORM_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF8
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF8() {
        return FORM_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF8
     *
     * @param FORM_SDEF8 the value for CG.EP_FORMWORK.FORM_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF8(String FORM_SDEF8) {
        this.FORM_SDEF8 = FORM_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF9
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF9() {
        return FORM_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF9
     *
     * @param FORM_SDEF9 the value for CG.EP_FORMWORK.FORM_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF9(String FORM_SDEF9) {
        this.FORM_SDEF9 = FORM_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF10
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF10() {
        return FORM_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF10
     *
     * @param FORM_SDEF10 the value for CG.EP_FORMWORK.FORM_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF10(String FORM_SDEF10) {
        this.FORM_SDEF10 = FORM_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF11
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF11() {
        return FORM_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF11
     *
     * @param FORM_SDEF11 the value for CG.EP_FORMWORK.FORM_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF11(String FORM_SDEF11) {
        this.FORM_SDEF11 = FORM_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF12
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF12() {
        return FORM_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF12
     *
     * @param FORM_SDEF12 the value for CG.EP_FORMWORK.FORM_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF12(String FORM_SDEF12) {
        this.FORM_SDEF12 = FORM_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF13
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF13() {
        return FORM_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF13
     *
     * @param FORM_SDEF13 the value for CG.EP_FORMWORK.FORM_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF13(String FORM_SDEF13) {
        this.FORM_SDEF13 = FORM_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF14
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF14() {
        return FORM_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF14
     *
     * @param FORM_SDEF14 the value for CG.EP_FORMWORK.FORM_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF14(String FORM_SDEF14) {
        this.FORM_SDEF14 = FORM_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF15
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF15() {
        return FORM_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF15
     *
     * @param FORM_SDEF15 the value for CG.EP_FORMWORK.FORM_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF15(String FORM_SDEF15) {
        this.FORM_SDEF15 = FORM_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF16
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF16() {
        return FORM_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF16
     *
     * @param FORM_SDEF16 the value for CG.EP_FORMWORK.FORM_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF16(String FORM_SDEF16) {
        this.FORM_SDEF16 = FORM_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF17
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF17() {
        return FORM_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF17
     *
     * @param FORM_SDEF17 the value for CG.EP_FORMWORK.FORM_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF17(String FORM_SDEF17) {
        this.FORM_SDEF17 = FORM_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF18
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF18() {
        return FORM_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF18
     *
     * @param FORM_SDEF18 the value for CG.EP_FORMWORK.FORM_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF18(String FORM_SDEF18) {
        this.FORM_SDEF18 = FORM_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF19
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF19() {
        return FORM_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF19
     *
     * @param FORM_SDEF19 the value for CG.EP_FORMWORK.FORM_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF19(String FORM_SDEF19) {
        this.FORM_SDEF19 = FORM_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_SDEF20
     *
     * @return the value of CG.EP_FORMWORK.FORM_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getFORM_SDEF20() {
        return FORM_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_SDEF20
     *
     * @param FORM_SDEF20 the value for CG.EP_FORMWORK.FORM_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_SDEF20(String FORM_SDEF20) {
        this.FORM_SDEF20 = FORM_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_NDEF1
     *
     * @return the value of CG.EP_FORMWORK.FORM_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getFORM_NDEF1() {
        return FORM_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_NDEF1
     *
     * @param FORM_NDEF1 the value for CG.EP_FORMWORK.FORM_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_NDEF1(BigDecimal FORM_NDEF1) {
        this.FORM_NDEF1 = FORM_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_NDEF2
     *
     * @return the value of CG.EP_FORMWORK.FORM_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getFORM_NDEF2() {
        return FORM_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_NDEF2
     *
     * @param FORM_NDEF2 the value for CG.EP_FORMWORK.FORM_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_NDEF2(BigDecimal FORM_NDEF2) {
        this.FORM_NDEF2 = FORM_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_NDEF3
     *
     * @return the value of CG.EP_FORMWORK.FORM_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getFORM_NDEF3() {
        return FORM_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_NDEF3
     *
     * @param FORM_NDEF3 the value for CG.EP_FORMWORK.FORM_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_NDEF3(BigDecimal FORM_NDEF3) {
        this.FORM_NDEF3 = FORM_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_NDEF4
     *
     * @return the value of CG.EP_FORMWORK.FORM_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getFORM_NDEF4() {
        return FORM_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_NDEF4
     *
     * @param FORM_NDEF4 the value for CG.EP_FORMWORK.FORM_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_NDEF4(BigDecimal FORM_NDEF4) {
        this.FORM_NDEF4 = FORM_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_NDEF5
     *
     * @return the value of CG.EP_FORMWORK.FORM_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getFORM_NDEF5() {
        return FORM_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_NDEF5
     *
     * @param FORM_NDEF5 the value for CG.EP_FORMWORK.FORM_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_NDEF5(BigDecimal FORM_NDEF5) {
        this.FORM_NDEF5 = FORM_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_TDEF1
     *
     * @return the value of CG.EP_FORMWORK.FORM_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_TDEF1() {
        return FORM_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_TDEF1
     *
     * @param FORM_TDEF1 the value for CG.EP_FORMWORK.FORM_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_TDEF1(Date FORM_TDEF1) {
        this.FORM_TDEF1 = FORM_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_TDEF2
     *
     * @return the value of CG.EP_FORMWORK.FORM_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_TDEF2() {
        return FORM_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_TDEF2
     *
     * @param FORM_TDEF2 the value for CG.EP_FORMWORK.FORM_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_TDEF2(Date FORM_TDEF2) {
        this.FORM_TDEF2 = FORM_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_TDEF3
     *
     * @return the value of CG.EP_FORMWORK.FORM_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_TDEF3() {
        return FORM_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_TDEF3
     *
     * @param FORM_TDEF3 the value for CG.EP_FORMWORK.FORM_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_TDEF3(Date FORM_TDEF3) {
        this.FORM_TDEF3 = FORM_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_TDEF4
     *
     * @return the value of CG.EP_FORMWORK.FORM_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_TDEF4() {
        return FORM_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_TDEF4
     *
     * @param FORM_TDEF4 the value for CG.EP_FORMWORK.FORM_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_TDEF4(Date FORM_TDEF4) {
        this.FORM_TDEF4 = FORM_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_FORMWORK.FORM_TDEF5
     *
     * @return the value of CG.EP_FORMWORK.FORM_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getFORM_TDEF5() {
        return FORM_TDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_FORMWORK.FORM_TDEF5
     *
     * @param FORM_TDEF5 the value for CG.EP_FORMWORK.FORM_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setFORM_TDEF5(Date FORM_TDEF5) {
        this.FORM_TDEF5 = FORM_TDEF5;
    }
}