package com.rc.project.form;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.util.Date;

import com.rc.project.vo.EpPackageList;
import com.rc.project.vo.EpProjectDetail;

public class EpPackageListForm {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.EP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.BG_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String BG_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.EPD_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EPD_NID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_NTYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NNUMOVER
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NNUMOVER;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SBRAND
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SBRAND;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SSPEC
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SSPEC;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SMODEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SMODEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SUNIT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SUNIT;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NNUM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NPRICE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NPRICE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NTOTAL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NNUMSONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NNUMSONG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NPRICESONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NPRICESONG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NTOTALSONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NTOTALSONG;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NNUMJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NNUMJIAN;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NPRICEJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NPRICEJIAN;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NTOTALJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NTOTALJIAN;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NCANNOT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NCANNOT;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SAPPROVENOTE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SAPPROVENOTE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SSTATUS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SSTATUS;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SISIMPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SISIMPORT;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SISFREETAX
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SISFREETAX;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SPARA
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SPARA;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SREMARK;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SBUYTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SBUYTYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SPAYTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SPAYTYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SBUYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_SBUYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SXYUNIT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_SXYUNIT;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SXYTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_SXYTOTAL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SXYMODEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SXYMODEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SXYBRAND
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SXYBRAND;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SXYNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SXYNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SXYYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SXYYEAR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PL_SDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PL_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_TDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_TDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_TDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_TDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PACKAGELIST.PL_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PL_TDEF5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.EP_SNO
     *
     * @return the value of CG.EP_PACKAGELIST.EP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SNO() {
        return EP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.EP_SNO
     *
     * @param EP_SNO the value for CG.EP_PACKAGELIST.EP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SNO(String EP_SNO) {
        this.EP_SNO = EP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.BG_SNO
     *
     * @return the value of CG.EP_PACKAGELIST.BG_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getBG_SNO() {
        return BG_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.BG_SNO
     *
     * @param BG_SNO the value for CG.EP_PACKAGELIST.BG_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setBG_SNO(String BG_SNO) {
        this.BG_SNO = BG_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.EPD_NID
     *
     * @return the value of CG.EP_PACKAGELIST.EPD_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEPD_NID() {
        return EPD_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.EPD_NID
     *
     * @param EPD_NID the value for CG.EP_PACKAGELIST.EPD_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEPD_NID(BigDecimal EPD_NID) {
        this.EPD_NID = EPD_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NNO
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NNO() {
        return PL_NNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NNO
     *
     * @param PL_NNO the value for CG.EP_PACKAGELIST.PL_NNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NNO(BigDecimal PL_NNO) {
        this.PL_NNO = PL_NNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SNAME
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SNAME() {
        return PL_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SNAME
     *
     * @param PL_SNAME the value for CG.EP_PACKAGELIST.PL_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SNAME(String PL_SNAME) {
        this.PL_SNAME = PL_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NTYPE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_NTYPE() {
        return PL_NTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NTYPE
     *
     * @param PL_NTYPE the value for CG.EP_PACKAGELIST.PL_NTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NTYPE(String PL_NTYPE) {
        this.PL_NTYPE = PL_NTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NNUMOVER
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NNUMOVER
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NNUMOVER() {
        return PL_NNUMOVER;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NNUMOVER
     *
     * @param PL_NNUMOVER the value for CG.EP_PACKAGELIST.PL_NNUMOVER
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NNUMOVER(BigDecimal PL_NNUMOVER) {
        this.PL_NNUMOVER = PL_NNUMOVER;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SBRAND
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SBRAND
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SBRAND() {
        return PL_SBRAND;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SBRAND
     *
     * @param PL_SBRAND the value for CG.EP_PACKAGELIST.PL_SBRAND
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SBRAND(String PL_SBRAND) {
        this.PL_SBRAND = PL_SBRAND;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SSPEC
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SSPEC
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SSPEC() {
        return PL_SSPEC;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SSPEC
     *
     * @param PL_SSPEC the value for CG.EP_PACKAGELIST.PL_SSPEC
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SSPEC(String PL_SSPEC) {
        this.PL_SSPEC = PL_SSPEC;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SMODEL
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SMODEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SMODEL() {
        return PL_SMODEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SMODEL
     *
     * @param PL_SMODEL the value for CG.EP_PACKAGELIST.PL_SMODEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SMODEL(String PL_SMODEL) {
        this.PL_SMODEL = PL_SMODEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SUNIT
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SUNIT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SUNIT() {
        return PL_SUNIT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SUNIT
     *
     * @param PL_SUNIT the value for CG.EP_PACKAGELIST.PL_SUNIT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SUNIT(String PL_SUNIT) {
        this.PL_SUNIT = PL_SUNIT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NNUM
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NNUM() {
        return PL_NNUM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NNUM
     *
     * @param PL_NNUM the value for CG.EP_PACKAGELIST.PL_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NNUM(BigDecimal PL_NNUM) {
        this.PL_NNUM = PL_NNUM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NPRICE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NPRICE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NPRICE() {
        return PL_NPRICE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NPRICE
     *
     * @param PL_NPRICE the value for CG.EP_PACKAGELIST.PL_NPRICE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NPRICE(BigDecimal PL_NPRICE) {
        this.PL_NPRICE = PL_NPRICE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NTOTAL
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NTOTAL() {
        return PL_NTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NTOTAL
     *
     * @param PL_NTOTAL the value for CG.EP_PACKAGELIST.PL_NTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NTOTAL(BigDecimal PL_NTOTAL) {
        this.PL_NTOTAL = PL_NTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NNUMSONG
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NNUMSONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NNUMSONG() {
        return PL_NNUMSONG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NNUMSONG
     *
     * @param PL_NNUMSONG the value for CG.EP_PACKAGELIST.PL_NNUMSONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NNUMSONG(BigDecimal PL_NNUMSONG) {
        this.PL_NNUMSONG = PL_NNUMSONG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NPRICESONG
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NPRICESONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NPRICESONG() {
        return PL_NPRICESONG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NPRICESONG
     *
     * @param PL_NPRICESONG the value for CG.EP_PACKAGELIST.PL_NPRICESONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NPRICESONG(BigDecimal PL_NPRICESONG) {
        this.PL_NPRICESONG = PL_NPRICESONG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NTOTALSONG
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NTOTALSONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NTOTALSONG() {
        return PL_NTOTALSONG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NTOTALSONG
     *
     * @param PL_NTOTALSONG the value for CG.EP_PACKAGELIST.PL_NTOTALSONG
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NTOTALSONG(BigDecimal PL_NTOTALSONG) {
        this.PL_NTOTALSONG = PL_NTOTALSONG;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NNUMJIAN
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NNUMJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NNUMJIAN() {
        return PL_NNUMJIAN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NNUMJIAN
     *
     * @param PL_NNUMJIAN the value for CG.EP_PACKAGELIST.PL_NNUMJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NNUMJIAN(BigDecimal PL_NNUMJIAN) {
        this.PL_NNUMJIAN = PL_NNUMJIAN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NPRICEJIAN
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NPRICEJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NPRICEJIAN() {
        return PL_NPRICEJIAN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NPRICEJIAN
     *
     * @param PL_NPRICEJIAN the value for CG.EP_PACKAGELIST.PL_NPRICEJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NPRICEJIAN(BigDecimal PL_NPRICEJIAN) {
        this.PL_NPRICEJIAN = PL_NPRICEJIAN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NTOTALJIAN
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NTOTALJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NTOTALJIAN() {
        return PL_NTOTALJIAN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NTOTALJIAN
     *
     * @param PL_NTOTALJIAN the value for CG.EP_PACKAGELIST.PL_NTOTALJIAN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NTOTALJIAN(BigDecimal PL_NTOTALJIAN) {
        this.PL_NTOTALJIAN = PL_NTOTALJIAN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NCANNOT
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NCANNOT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NCANNOT() {
        return PL_NCANNOT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NCANNOT
     *
     * @param PL_NCANNOT the value for CG.EP_PACKAGELIST.PL_NCANNOT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NCANNOT(BigDecimal PL_NCANNOT) {
        this.PL_NCANNOT = PL_NCANNOT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SAPPROVENOTE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SAPPROVENOTE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SAPPROVENOTE() {
        return PL_SAPPROVENOTE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SAPPROVENOTE
     *
     * @param PL_SAPPROVENOTE the value for CG.EP_PACKAGELIST.PL_SAPPROVENOTE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SAPPROVENOTE(String PL_SAPPROVENOTE) {
        this.PL_SAPPROVENOTE = PL_SAPPROVENOTE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SSTATUS
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SSTATUS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SSTATUS() {
        return PL_SSTATUS;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SSTATUS
     *
     * @param PL_SSTATUS the value for CG.EP_PACKAGELIST.PL_SSTATUS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SSTATUS(String PL_SSTATUS) {
        this.PL_SSTATUS = PL_SSTATUS;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SISIMPORT
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SISIMPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SISIMPORT() {
        return PL_SISIMPORT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SISIMPORT
     *
     * @param PL_SISIMPORT the value for CG.EP_PACKAGELIST.PL_SISIMPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SISIMPORT(String PL_SISIMPORT) {
        this.PL_SISIMPORT = PL_SISIMPORT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SISFREETAX
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SISFREETAX
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SISFREETAX() {
        return PL_SISFREETAX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SISFREETAX
     *
     * @param PL_SISFREETAX the value for CG.EP_PACKAGELIST.PL_SISFREETAX
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SISFREETAX(String PL_SISFREETAX) {
        this.PL_SISFREETAX = PL_SISFREETAX;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SPARA
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SPARA
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SPARA() {
        return PL_SPARA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SPARA
     *
     * @param PL_SPARA the value for CG.EP_PACKAGELIST.PL_SPARA
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SPARA(String PL_SPARA) {
        this.PL_SPARA = PL_SPARA;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SREMARK
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SREMARK() {
        return PL_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SREMARK
     *
     * @param PL_SREMARK the value for CG.EP_PACKAGELIST.PL_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SREMARK(String PL_SREMARK) {
        this.PL_SREMARK = PL_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SBUYTYPE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SBUYTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SBUYTYPE() {
        return PL_SBUYTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SBUYTYPE
     *
     * @param PL_SBUYTYPE the value for CG.EP_PACKAGELIST.PL_SBUYTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SBUYTYPE(String PL_SBUYTYPE) {
        this.PL_SBUYTYPE = PL_SBUYTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SPAYTYPE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SPAYTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SPAYTYPE() {
        return PL_SPAYTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SPAYTYPE
     *
     * @param PL_SPAYTYPE the value for CG.EP_PACKAGELIST.PL_SPAYTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SPAYTYPE(String PL_SPAYTYPE) {
        this.PL_SPAYTYPE = PL_SPAYTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SBUYDATE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SBUYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_SBUYDATE() {
        return PL_SBUYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SBUYDATE
     *
     * @param PL_SBUYDATE the value for CG.EP_PACKAGELIST.PL_SBUYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SBUYDATE(Date PL_SBUYDATE) {
        this.PL_SBUYDATE = PL_SBUYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SXYUNIT
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SXYUNIT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_SXYUNIT() {
        return PL_SXYUNIT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SXYUNIT
     *
     * @param PL_SXYUNIT the value for CG.EP_PACKAGELIST.PL_SXYUNIT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SXYUNIT(BigDecimal PL_SXYUNIT) {
        this.PL_SXYUNIT = PL_SXYUNIT;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SXYTOTAL
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SXYTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_SXYTOTAL() {
        return PL_SXYTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SXYTOTAL
     *
     * @param PL_SXYTOTAL the value for CG.EP_PACKAGELIST.PL_SXYTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SXYTOTAL(BigDecimal PL_SXYTOTAL) {
        this.PL_SXYTOTAL = PL_SXYTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SXYMODEL
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SXYMODEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SXYMODEL() {
        return PL_SXYMODEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SXYMODEL
     *
     * @param PL_SXYMODEL the value for CG.EP_PACKAGELIST.PL_SXYMODEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SXYMODEL(String PL_SXYMODEL) {
        this.PL_SXYMODEL = PL_SXYMODEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SXYBRAND
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SXYBRAND
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SXYBRAND() {
        return PL_SXYBRAND;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SXYBRAND
     *
     * @param PL_SXYBRAND the value for CG.EP_PACKAGELIST.PL_SXYBRAND
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SXYBRAND(String PL_SXYBRAND) {
        this.PL_SXYBRAND = PL_SXYBRAND;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SXYNO
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SXYNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SXYNO() {
        return PL_SXYNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SXYNO
     *
     * @param PL_SXYNO the value for CG.EP_PACKAGELIST.PL_SXYNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SXYNO(String PL_SXYNO) {
        this.PL_SXYNO = PL_SXYNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SXYYEAR
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SXYYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SXYYEAR() {
        return PL_SXYYEAR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SXYYEAR
     *
     * @param PL_SXYYEAR the value for CG.EP_PACKAGELIST.PL_SXYYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SXYYEAR(String PL_SXYYEAR) {
        this.PL_SXYYEAR = PL_SXYYEAR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SISDEL
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SISDEL() {
        return PL_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SISDEL
     *
     * @param PL_SISDEL the value for CG.EP_PACKAGELIST.PL_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SISDEL(String PL_SISDEL) {
        this.PL_SISDEL = PL_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SISVALID
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SISVALID() {
        return PL_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SISVALID
     *
     * @param PL_SISVALID the value for CG.EP_PACKAGELIST.PL_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SISVALID(String PL_SISVALID) {
        this.PL_SISVALID = PL_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SREPLYBY
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SREPLYBY() {
        return PL_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SREPLYBY
     *
     * @param PL_SREPLYBY the value for CG.EP_PACKAGELIST.PL_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SREPLYBY(String PL_SREPLYBY) {
        this.PL_SREPLYBY = PL_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SREPLYDATE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_SREPLYDATE() {
        return PL_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SREPLYDATE
     *
     * @param PL_SREPLYDATE the value for CG.EP_PACKAGELIST.PL_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SREPLYDATE(Date PL_SREPLYDATE) {
        this.PL_SREPLYDATE = PL_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SALTERBY
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SALTERBY() {
        return PL_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SALTERBY
     *
     * @param PL_SALTERBY the value for CG.EP_PACKAGELIST.PL_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SALTERBY(String PL_SALTERBY) {
        this.PL_SALTERBY = PL_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SALTERDATE
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_SALTERDATE() {
        return PL_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SALTERDATE
     *
     * @param PL_SALTERDATE the value for CG.EP_PACKAGELIST.PL_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SALTERDATE(Date PL_SALTERDATE) {
        this.PL_SALTERDATE = PL_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF1
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF1() {
        return PL_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF1
     *
     * @param PL_SDEF1 the value for CG.EP_PACKAGELIST.PL_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF1(String PL_SDEF1) {
        this.PL_SDEF1 = PL_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF4
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF4() {
        return PL_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF4
     *
     * @param PL_SDEF4 the value for CG.EP_PACKAGELIST.PL_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF4(String PL_SDEF4) {
        this.PL_SDEF4 = PL_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF5
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF5() {
        return PL_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF5
     *
     * @param PL_SDEF5 the value for CG.EP_PACKAGELIST.PL_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF5(String PL_SDEF5) {
        this.PL_SDEF5 = PL_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF6
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF6() {
        return PL_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF6
     *
     * @param PL_SDEF6 the value for CG.EP_PACKAGELIST.PL_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF6(String PL_SDEF6) {
        this.PL_SDEF6 = PL_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF7
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF7() {
        return PL_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF7
     *
     * @param PL_SDEF7 the value for CG.EP_PACKAGELIST.PL_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF7(String PL_SDEF7) {
        this.PL_SDEF7 = PL_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF8
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF8() {
        return PL_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF8
     *
     * @param PL_SDEF8 the value for CG.EP_PACKAGELIST.PL_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF8(String PL_SDEF8) {
        this.PL_SDEF8 = PL_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF9
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF9() {
        return PL_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF9
     *
     * @param PL_SDEF9 the value for CG.EP_PACKAGELIST.PL_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF9(String PL_SDEF9) {
        this.PL_SDEF9 = PL_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF10
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF10() {
        return PL_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF10
     *
     * @param PL_SDEF10 the value for CG.EP_PACKAGELIST.PL_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF10(String PL_SDEF10) {
        this.PL_SDEF10 = PL_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF11
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF11() {
        return PL_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF11
     *
     * @param PL_SDEF11 the value for CG.EP_PACKAGELIST.PL_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF11(String PL_SDEF11) {
        this.PL_SDEF11 = PL_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF12
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF12() {
        return PL_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF12
     *
     * @param PL_SDEF12 the value for CG.EP_PACKAGELIST.PL_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF12(String PL_SDEF12) {
        this.PL_SDEF12 = PL_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF13
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF13() {
        return PL_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF13
     *
     * @param PL_SDEF13 the value for CG.EP_PACKAGELIST.PL_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF13(String PL_SDEF13) {
        this.PL_SDEF13 = PL_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF14
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF14() {
        return PL_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF14
     *
     * @param PL_SDEF14 the value for CG.EP_PACKAGELIST.PL_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF14(String PL_SDEF14) {
        this.PL_SDEF14 = PL_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF15
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF15() {
        return PL_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF15
     *
     * @param PL_SDEF15 the value for CG.EP_PACKAGELIST.PL_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF15(String PL_SDEF15) {
        this.PL_SDEF15 = PL_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF16
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF16() {
        return PL_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF16
     *
     * @param PL_SDEF16 the value for CG.EP_PACKAGELIST.PL_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF16(String PL_SDEF16) {
        this.PL_SDEF16 = PL_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF17
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF17() {
        return PL_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF17
     *
     * @param PL_SDEF17 the value for CG.EP_PACKAGELIST.PL_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF17(String PL_SDEF17) {
        this.PL_SDEF17 = PL_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF18
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF18() {
        return PL_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF18
     *
     * @param PL_SDEF18 the value for CG.EP_PACKAGELIST.PL_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF18(String PL_SDEF18) {
        this.PL_SDEF18 = PL_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF19
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF19() {
        return PL_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF19
     *
     * @param PL_SDEF19 the value for CG.EP_PACKAGELIST.PL_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF19(String PL_SDEF19) {
        this.PL_SDEF19 = PL_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_SDEF20
     *
     * @return the value of CG.EP_PACKAGELIST.PL_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPL_SDEF20() {
        return PL_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_SDEF20
     *
     * @param PL_SDEF20 the value for CG.EP_PACKAGELIST.PL_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_SDEF20(String PL_SDEF20) {
        this.PL_SDEF20 = PL_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NDEF1
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NDEF1() {
        return PL_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NDEF1
     *
     * @param PL_NDEF1 the value for CG.EP_PACKAGELIST.PL_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NDEF1(BigDecimal PL_NDEF1) {
        this.PL_NDEF1 = PL_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NDEF2
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NDEF2() {
        return PL_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NDEF2
     *
     * @param PL_NDEF2 the value for CG.EP_PACKAGELIST.PL_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NDEF2(BigDecimal PL_NDEF2) {
        this.PL_NDEF2 = PL_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NDEF3
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NDEF3() {
        return PL_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NDEF3
     *
     * @param PL_NDEF3 the value for CG.EP_PACKAGELIST.PL_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NDEF3(BigDecimal PL_NDEF3) {
        this.PL_NDEF3 = PL_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NDEF4
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NDEF4() {
        return PL_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NDEF4
     *
     * @param PL_NDEF4 the value for CG.EP_PACKAGELIST.PL_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NDEF4(BigDecimal PL_NDEF4) {
        this.PL_NDEF4 = PL_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_NDEF5
     *
     * @return the value of CG.EP_PACKAGELIST.PL_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPL_NDEF5() {
        return PL_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_NDEF5
     *
     * @param PL_NDEF5 the value for CG.EP_PACKAGELIST.PL_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_NDEF5(BigDecimal PL_NDEF5) {
        this.PL_NDEF5 = PL_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_TDEF1
     *
     * @return the value of CG.EP_PACKAGELIST.PL_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_TDEF1() {
        return PL_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_TDEF1
     *
     * @param PL_TDEF1 the value for CG.EP_PACKAGELIST.PL_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_TDEF1(Date PL_TDEF1) {
        this.PL_TDEF1 = PL_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_TDEF2
     *
     * @return the value of CG.EP_PACKAGELIST.PL_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_TDEF2() {
        return PL_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_TDEF2
     *
     * @param PL_TDEF2 the value for CG.EP_PACKAGELIST.PL_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_TDEF2(Date PL_TDEF2) {
        this.PL_TDEF2 = PL_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_TDEF3
     *
     * @return the value of CG.EP_PACKAGELIST.PL_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_TDEF3() {
        return PL_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_TDEF3
     *
     * @param PL_TDEF3 the value for CG.EP_PACKAGELIST.PL_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_TDEF3(Date PL_TDEF3) {
        this.PL_TDEF3 = PL_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_TDEF4
     *
     * @return the value of CG.EP_PACKAGELIST.PL_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_TDEF4() {
        return PL_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_TDEF4
     *
     * @param PL_TDEF4 the value for CG.EP_PACKAGELIST.PL_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_TDEF4(Date PL_TDEF4) {
        this.PL_TDEF4 = PL_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PACKAGELIST.PL_TDEF5
     *
     * @return the value of CG.EP_PACKAGELIST.PL_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPL_TDEF5() {
        return PL_TDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PACKAGELIST.PL_TDEF5
     *
     * @param PL_TDEF5 the value for CG.EP_PACKAGELIST.PL_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPL_TDEF5(Date PL_TDEF5) {
        this.PL_TDEF5 = PL_TDEF5;
    }
    
    public EpPackageList toVO() {
		try {

			EpPackageList vo = new EpPackageList();
			EpPackageListForm.class.getFields();
			for (Field field : EpPackageList.class.getDeclaredFields()) {
				Field sField = EpPackageListForm.class.getDeclaredField(field.getName());
				if (sField != null) {
					sField.setAccessible(true);
					field.setAccessible(true);
					Object value = sField.get(this);
					field.set(vo, value);
				}

			}
			return vo;
		} catch (Exception e) {
			throw new RuntimeException(e);
		}

	}
    
}