package com.rc.project.form;

import java.math.BigDecimal;
import java.util.Date;

import com.rc.base.form.MngEmpForm;
import com.rc.base.form.MngUnitDepartForm;

/**
 * @author Administrator
 *
 */
public class EpPersonForm {
	
	private String PageSQLA;
	private String PageSQLB;
	private String searchA;
	private String searchB;
	private String searchC;
	

	public String getSearchA() {
		return searchA;
	}

	public void setSearchA(String searchA) {
		this.searchA = searchA;
	}

	public String getSearchB() {
		return searchB;
	}

	public void setSearchB(String searchB) {
		this.searchB = searchB;
	}

	public String getSearchC() {
		return searchC;
	}

	public void setSearchC(String searchC) {
		this.searchC = searchC;
	}

	public String getPageSQLA() {
		return PageSQLA;
	}

	public void setPageSQLA(String setPageSQLA) {
		this.PageSQLA = setPageSQLA;
	}

	public String getPageSQLB() {
		return PageSQLB;
	}

	public void setPageSQLB(String setPageSQLB) {
		this.PageSQLB = setPageSQLB;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private int PER_NID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String UD_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EMP_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_STYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_STYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.UD_SNO1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String UD_SNO1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SREMARK;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String PER_SDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PER_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PER_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PER_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PER_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal PER_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_TDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_TDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_TDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_TDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PERSON.PER_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date PER_TDEF5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_NID
     *
     * @return the value of CG.EP_PERSON.PER_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int getPER_NID() {
        return PER_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_NID
     *
     * @param PER_NID the value for CG.EP_PERSON.PER_NID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_NID(int PER_NID) {
        this.PER_NID = PER_NID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.UD_SNO
     *
     * @return the value of CG.EP_PERSON.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getUD_SNO() {
        return UD_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.UD_SNO
     *
     * @param UD_SNO the value for CG.EP_PERSON.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setUD_SNO(String UD_SNO) {
        this.UD_SNO = UD_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.EMP_SNO
     *
     * @return the value of CG.EP_PERSON.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEMP_SNO() {
        return EMP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.EMP_SNO
     *
     * @param EMP_SNO the value for CG.EP_PERSON.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEMP_SNO(String EMP_SNO) {
        this.EMP_SNO = EMP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_STYPE
     *
     * @return the value of CG.EP_PERSON.PER_STYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_STYPE() {
        return PER_STYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_STYPE
     *
     * @param PER_STYPE the value for CG.EP_PERSON.PER_STYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_STYPE(String PER_STYPE) {
        this.PER_STYPE = PER_STYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.UD_SNO1
     *
     * @return the value of CG.EP_PERSON.UD_SNO1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getUD_SNO1() {
        return UD_SNO1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.UD_SNO1
     *
     * @param UD_SNO1 the value for CG.EP_PERSON.UD_SNO1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setUD_SNO1(String UD_SNO1) {
        this.UD_SNO1 = UD_SNO1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SREMARK
     *
     * @return the value of CG.EP_PERSON.PER_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SREMARK() {
        return PER_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SREMARK
     *
     * @param PER_SREMARK the value for CG.EP_PERSON.PER_SREMARK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SREMARK(String PER_SREMARK) {
        this.PER_SREMARK = PER_SREMARK;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SISDEL
     *
     * @return the value of CG.EP_PERSON.PER_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SISDEL() {
        return PER_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SISDEL
     *
     * @param PER_SISDEL the value for CG.EP_PERSON.PER_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SISDEL(String PER_SISDEL) {
        this.PER_SISDEL = PER_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SISVALID
     *
     * @return the value of CG.EP_PERSON.PER_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SISVALID() {
        return PER_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SISVALID
     *
     * @param PER_SISVALID the value for CG.EP_PERSON.PER_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SISVALID(String PER_SISVALID) {
        this.PER_SISVALID = PER_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SREPLYBY
     *
     * @return the value of CG.EP_PERSON.PER_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SREPLYBY() {
        return PER_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SREPLYBY
     *
     * @param PER_SREPLYBY the value for CG.EP_PERSON.PER_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SREPLYBY(String PER_SREPLYBY) {
        this.PER_SREPLYBY = PER_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SREPLYDATE
     *
     * @return the value of CG.EP_PERSON.PER_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_SREPLYDATE() {
        return PER_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SREPLYDATE
     *
     * @param PER_SREPLYDATE the value for CG.EP_PERSON.PER_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SREPLYDATE(Date PER_SREPLYDATE) {
        this.PER_SREPLYDATE = PER_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SALTERBY
     *
     * @return the value of CG.EP_PERSON.PER_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SALTERBY() {
        return PER_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SALTERBY
     *
     * @param PER_SALTERBY the value for CG.EP_PERSON.PER_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SALTERBY(String PER_SALTERBY) {
        this.PER_SALTERBY = PER_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SALTERDATE
     *
     * @return the value of CG.EP_PERSON.PER_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_SALTERDATE() {
        return PER_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SALTERDATE
     *
     * @param PER_SALTERDATE the value for CG.EP_PERSON.PER_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SALTERDATE(Date PER_SALTERDATE) {
        this.PER_SALTERDATE = PER_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF1
     *
     * @return the value of CG.EP_PERSON.PER_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF1() {
        return PER_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF1
     *
     * @param PER_SDEF1 the value for CG.EP_PERSON.PER_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF1(String PER_SDEF1) {
        this.PER_SDEF1 = PER_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF2
     *
     * @return the value of CG.EP_PERSON.PER_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF2() {
        return PER_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF2
     *
     * @param PER_SDEF2 the value for CG.EP_PERSON.PER_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF2(String PER_SDEF2) {
        this.PER_SDEF2 = PER_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF3
     *
     * @return the value of CG.EP_PERSON.PER_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF3() {
        return PER_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF3
     *
     * @param PER_SDEF3 the value for CG.EP_PERSON.PER_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF3(String PER_SDEF3) {
        this.PER_SDEF3 = PER_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF4
     *
     * @return the value of CG.EP_PERSON.PER_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF4() {
        return PER_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF4
     *
     * @param PER_SDEF4 the value for CG.EP_PERSON.PER_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF4(String PER_SDEF4) {
        this.PER_SDEF4 = PER_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF5
     *
     * @return the value of CG.EP_PERSON.PER_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF5() {
        return PER_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF5
     *
     * @param PER_SDEF5 the value for CG.EP_PERSON.PER_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF5(String PER_SDEF5) {
        this.PER_SDEF5 = PER_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF6
     *
     * @return the value of CG.EP_PERSON.PER_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF6() {
        return PER_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF6
     *
     * @param PER_SDEF6 the value for CG.EP_PERSON.PER_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF6(String PER_SDEF6) {
        this.PER_SDEF6 = PER_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF7
     *
     * @return the value of CG.EP_PERSON.PER_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF7() {
        return PER_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF7
     *
     * @param PER_SDEF7 the value for CG.EP_PERSON.PER_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF7(String PER_SDEF7) {
        this.PER_SDEF7 = PER_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF8
     *
     * @return the value of CG.EP_PERSON.PER_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF8() {
        return PER_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF8
     *
     * @param PER_SDEF8 the value for CG.EP_PERSON.PER_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF8(String PER_SDEF8) {
        this.PER_SDEF8 = PER_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF9
     *
     * @return the value of CG.EP_PERSON.PER_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF9() {
        return PER_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF9
     *
     * @param PER_SDEF9 the value for CG.EP_PERSON.PER_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF9(String PER_SDEF9) {
        this.PER_SDEF9 = PER_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF10
     *
     * @return the value of CG.EP_PERSON.PER_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF10() {
        return PER_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF10
     *
     * @param PER_SDEF10 the value for CG.EP_PERSON.PER_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF10(String PER_SDEF10) {
        this.PER_SDEF10 = PER_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF11
     *
     * @return the value of CG.EP_PERSON.PER_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF11() {
        return PER_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF11
     *
     * @param PER_SDEF11 the value for CG.EP_PERSON.PER_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF11(String PER_SDEF11) {
        this.PER_SDEF11 = PER_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF12
     *
     * @return the value of CG.EP_PERSON.PER_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF12() {
        return PER_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF12
     *
     * @param PER_SDEF12 the value for CG.EP_PERSON.PER_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF12(String PER_SDEF12) {
        this.PER_SDEF12 = PER_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF13
     *
     * @return the value of CG.EP_PERSON.PER_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF13() {
        return PER_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF13
     *
     * @param PER_SDEF13 the value for CG.EP_PERSON.PER_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF13(String PER_SDEF13) {
        this.PER_SDEF13 = PER_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF14
     *
     * @return the value of CG.EP_PERSON.PER_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF14() {
        return PER_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF14
     *
     * @param PER_SDEF14 the value for CG.EP_PERSON.PER_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF14(String PER_SDEF14) {
        this.PER_SDEF14 = PER_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF15
     *
     * @return the value of CG.EP_PERSON.PER_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF15() {
        return PER_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF15
     *
     * @param PER_SDEF15 the value for CG.EP_PERSON.PER_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF15(String PER_SDEF15) {
        this.PER_SDEF15 = PER_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF16
     *
     * @return the value of CG.EP_PERSON.PER_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF16() {
        return PER_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF16
     *
     * @param PER_SDEF16 the value for CG.EP_PERSON.PER_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF16(String PER_SDEF16) {
        this.PER_SDEF16 = PER_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF17
     *
     * @return the value of CG.EP_PERSON.PER_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF17() {
        return PER_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF17
     *
     * @param PER_SDEF17 the value for CG.EP_PERSON.PER_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF17(String PER_SDEF17) {
        this.PER_SDEF17 = PER_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF18
     *
     * @return the value of CG.EP_PERSON.PER_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF18() {
        return PER_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF18
     *
     * @param PER_SDEF18 the value for CG.EP_PERSON.PER_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF18(String PER_SDEF18) {
        this.PER_SDEF18 = PER_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF19
     *
     * @return the value of CG.EP_PERSON.PER_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF19() {
        return PER_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF19
     *
     * @param PER_SDEF19 the value for CG.EP_PERSON.PER_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF19(String PER_SDEF19) {
        this.PER_SDEF19 = PER_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_SDEF20
     *
     * @return the value of CG.EP_PERSON.PER_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getPER_SDEF20() {
        return PER_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_SDEF20
     *
     * @param PER_SDEF20 the value for CG.EP_PERSON.PER_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_SDEF20(String PER_SDEF20) {
        this.PER_SDEF20 = PER_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_NDEF1
     *
     * @return the value of CG.EP_PERSON.PER_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPER_NDEF1() {
        return PER_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_NDEF1
     *
     * @param PER_NDEF1 the value for CG.EP_PERSON.PER_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_NDEF1(BigDecimal PER_NDEF1) {
        this.PER_NDEF1 = PER_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_NDEF2
     *
     * @return the value of CG.EP_PERSON.PER_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPER_NDEF2() {
        return PER_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_NDEF2
     *
     * @param PER_NDEF2 the value for CG.EP_PERSON.PER_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_NDEF2(BigDecimal PER_NDEF2) {
        this.PER_NDEF2 = PER_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_NDEF3
     *
     * @return the value of CG.EP_PERSON.PER_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPER_NDEF3() {
        return PER_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_NDEF3
     *
     * @param PER_NDEF3 the value for CG.EP_PERSON.PER_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_NDEF3(BigDecimal PER_NDEF3) {
        this.PER_NDEF3 = PER_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_NDEF4
     *
     * @return the value of CG.EP_PERSON.PER_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPER_NDEF4() {
        return PER_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_NDEF4
     *
     * @param PER_NDEF4 the value for CG.EP_PERSON.PER_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_NDEF4(BigDecimal PER_NDEF4) {
        this.PER_NDEF4 = PER_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_NDEF5
     *
     * @return the value of CG.EP_PERSON.PER_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getPER_NDEF5() {
        return PER_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_NDEF5
     *
     * @param PER_NDEF5 the value for CG.EP_PERSON.PER_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_NDEF5(BigDecimal PER_NDEF5) {
        this.PER_NDEF5 = PER_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_TDEF1
     *
     * @return the value of CG.EP_PERSON.PER_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_TDEF1() {
        return PER_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_TDEF1
     *
     * @param PER_TDEF1 the value for CG.EP_PERSON.PER_TDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_TDEF1(Date PER_TDEF1) {
        this.PER_TDEF1 = PER_TDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_TDEF2
     *
     * @return the value of CG.EP_PERSON.PER_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_TDEF2() {
        return PER_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_TDEF2
     *
     * @param PER_TDEF2 the value for CG.EP_PERSON.PER_TDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_TDEF2(Date PER_TDEF2) {
        this.PER_TDEF2 = PER_TDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_TDEF3
     *
     * @return the value of CG.EP_PERSON.PER_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_TDEF3() {
        return PER_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_TDEF3
     *
     * @param PER_TDEF3 the value for CG.EP_PERSON.PER_TDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_TDEF3(Date PER_TDEF3) {
        this.PER_TDEF3 = PER_TDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_TDEF4
     *
     * @return the value of CG.EP_PERSON.PER_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_TDEF4() {
        return PER_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_TDEF4
     *
     * @param PER_TDEF4 the value for CG.EP_PERSON.PER_TDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_TDEF4(Date PER_TDEF4) {
        this.PER_TDEF4 = PER_TDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PERSON.PER_TDEF5
     *
     * @return the value of CG.EP_PERSON.PER_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getPER_TDEF5() {
        return PER_TDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PERSON.PER_TDEF5
     *
     * @param PER_TDEF5 the value for CG.EP_PERSON.PER_TDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setPER_TDEF5(Date PER_TDEF5) {
        this.PER_TDEF5 = PER_TDEF5;
    }
}