package com.rc.project.form;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.util.Date;

import com.rc.project.vo.EpProjectDetail;

public class EpProjectDetailForm {
	private String searchA;
	private String PageSQLA;
	private String PageSQLB;
	
	public String getSearchA() {
		return searchA;
	}

	public void setSearchA(String searchA) {
		this.searchA = searchA;
	}

	public String getPageSQLA() {
		return PageSQLA;
	}

	public void setPageSQLA(String pageSQLA) {
		PageSQLA = pageSQLA;
	}

	public String getPageSQLB() {
		return PageSQLB;
	}

	public void setPageSQLB(String pageSQLB) {
		PageSQLB = pageSQLB;
	}
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NID
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NID;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EP_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EP_SNO;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NID
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NID
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NID() {
		return EPD_NID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NID
	 * @param EPD_NID  the value for CG.EP_PROJECTDETAIL.EPD_NID
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NID(BigDecimal EPD_NID) {
		this.EPD_NID = EPD_NID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EP_SNO
	 * @return  the value of CG.EP_PROJECTDETAIL.EP_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEP_SNO() {
		return EP_SNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EP_SNO
	 * @param EP_SNO  the value for CG.EP_PROJECTDETAIL.EP_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEP_SNO(String EP_SNO) {
		this.EP_SNO = EP_SNO;
	}
	
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SASKNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SASKNO;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.RP_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String RP_SNO;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SYEAR
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SYEAR;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.UD_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String UD_SNO;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SREPORTUNITNAME
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SREPORTUNITNAME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NNO;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SNAME
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SNAME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SNAMEXIAO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SNAMEXIAO;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SMODEL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SMODEL;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SSPEC
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SSPEC;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SBRAND
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SBRAND;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SUNIT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SUNIT;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NNUM
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NNUM;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NPRICE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NPRICE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NTOTAL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NTOTAL;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NNUMSONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NNUMSONG;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NPRICESONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NPRICESONG;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NTOTALSONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NTOTALSONG;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NNUMJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NNUMJIAN;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NPRICEJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NPRICEJIAN;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NTOTALJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NTOTALJIAN;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NCANNOT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NCANNOT;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SAPPROVENOTE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SAPPROVENOTE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SSTAT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SSTAT;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SPURTYPE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SPURTYPE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SISIMPORT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SISIMPORT;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SISFREETAX
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SISFREETAX;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SJKFILE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SJKFILE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SMSFILE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SMSFILE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.PL_SPARA
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String PL_SPARA;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.PL_SREMARK
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String PL_SREMARK;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.PL_SPAYTYPE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String PL_SPAYTYPE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.PL_SBUYDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date PL_SBUYDATE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SISDEL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SISDEL;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SISVALID
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SISVALID;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SREPLYBY
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SREPLYBY;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SREPLYDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_SREPLYDATE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SALTERBY
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SALTERBY;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SALTERDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_SALTERDATE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF6
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF7
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF8
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF9
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF10
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF11
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF11;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF12
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF12;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF13
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF13;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF14
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF14;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF15
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF15;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF16
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF16;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF17
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF17;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF18
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF18;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF19
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF19;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_SDEF20
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private String EPD_SDEF20;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF6
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF7
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF8
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF9
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_NDEF10
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private BigDecimal EPD_NDEF10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_DDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_DDEF1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_DDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_DDEF2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_DDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_DDEF3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_DDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_DDEF4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CG.EP_PROJECTDETAIL.EPD_DDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	private Date EPD_DDEF5;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SASKNO
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SASKNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SASKNO() {
		return EPD_SASKNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SASKNO
	 * @param EPD_SASKNO  the value for CG.EP_PROJECTDETAIL.EPD_SASKNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SASKNO(String EPD_SASKNO) {
		this.EPD_SASKNO = EPD_SASKNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.RP_SNO
	 * @return  the value of CG.EP_PROJECTDETAIL.RP_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getRP_SNO() {
		return RP_SNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.RP_SNO
	 * @param RP_SNO  the value for CG.EP_PROJECTDETAIL.RP_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setRP_SNO(String RP_SNO) {
		this.RP_SNO = RP_SNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SYEAR
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SYEAR
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SYEAR() {
		return EPD_SYEAR;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SYEAR
	 * @param EPD_SYEAR  the value for CG.EP_PROJECTDETAIL.EPD_SYEAR
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SYEAR(String EPD_SYEAR) {
		this.EPD_SYEAR = EPD_SYEAR;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.UD_SNO
	 * @return  the value of CG.EP_PROJECTDETAIL.UD_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getUD_SNO() {
		return UD_SNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.UD_SNO
	 * @param UD_SNO  the value for CG.EP_PROJECTDETAIL.UD_SNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setUD_SNO(String UD_SNO) {
		this.UD_SNO = UD_SNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SREPORTUNITNAME
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SREPORTUNITNAME
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SREPORTUNITNAME() {
		return EPD_SREPORTUNITNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SREPORTUNITNAME
	 * @param EPD_SREPORTUNITNAME  the value for CG.EP_PROJECTDETAIL.EPD_SREPORTUNITNAME
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SREPORTUNITNAME(String EPD_SREPORTUNITNAME) {
		this.EPD_SREPORTUNITNAME = EPD_SREPORTUNITNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NNO
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NNO() {
		return EPD_NNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NNO
	 * @param EPD_NNO  the value for CG.EP_PROJECTDETAIL.EPD_NNO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NNO(BigDecimal EPD_NNO) {
		this.EPD_NNO = EPD_NNO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SNAME
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SNAME
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SNAME() {
		return EPD_SNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SNAME
	 * @param EPD_SNAME  the value for CG.EP_PROJECTDETAIL.EPD_SNAME
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SNAME(String EPD_SNAME) {
		this.EPD_SNAME = EPD_SNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SNAMEXIAO
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SNAMEXIAO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SNAMEXIAO() {
		return EPD_SNAMEXIAO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SNAMEXIAO
	 * @param EPD_SNAMEXIAO  the value for CG.EP_PROJECTDETAIL.EPD_SNAMEXIAO
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SNAMEXIAO(String EPD_SNAMEXIAO) {
		this.EPD_SNAMEXIAO = EPD_SNAMEXIAO;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SMODEL
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SMODEL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SMODEL() {
		return EPD_SMODEL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SMODEL
	 * @param EPD_SMODEL  the value for CG.EP_PROJECTDETAIL.EPD_SMODEL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SMODEL(String EPD_SMODEL) {
		this.EPD_SMODEL = EPD_SMODEL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SSPEC
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SSPEC
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SSPEC() {
		return EPD_SSPEC;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SSPEC
	 * @param EPD_SSPEC  the value for CG.EP_PROJECTDETAIL.EPD_SSPEC
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SSPEC(String EPD_SSPEC) {
		this.EPD_SSPEC = EPD_SSPEC;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SBRAND
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SBRAND
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SBRAND() {
		return EPD_SBRAND;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SBRAND
	 * @param EPD_SBRAND  the value for CG.EP_PROJECTDETAIL.EPD_SBRAND
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SBRAND(String EPD_SBRAND) {
		this.EPD_SBRAND = EPD_SBRAND;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SUNIT
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SUNIT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SUNIT() {
		return EPD_SUNIT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SUNIT
	 * @param EPD_SUNIT  the value for CG.EP_PROJECTDETAIL.EPD_SUNIT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SUNIT(String EPD_SUNIT) {
		this.EPD_SUNIT = EPD_SUNIT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NNUM
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NNUM
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NNUM() {
		return EPD_NNUM;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NNUM
	 * @param EPD_NNUM  the value for CG.EP_PROJECTDETAIL.EPD_NNUM
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NNUM(BigDecimal EPD_NNUM) {
		this.EPD_NNUM = EPD_NNUM;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NPRICE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NPRICE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NPRICE() {
		return EPD_NPRICE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NPRICE
	 * @param EPD_NPRICE  the value for CG.EP_PROJECTDETAIL.EPD_NPRICE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NPRICE(BigDecimal EPD_NPRICE) {
		this.EPD_NPRICE = EPD_NPRICE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NTOTAL
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NTOTAL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NTOTAL() {
		return EPD_NTOTAL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NTOTAL
	 * @param EPD_NTOTAL  the value for CG.EP_PROJECTDETAIL.EPD_NTOTAL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NTOTAL(BigDecimal EPD_NTOTAL) {
		this.EPD_NTOTAL = EPD_NTOTAL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NNUMSONG
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NNUMSONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NNUMSONG() {
		return EPD_NNUMSONG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NNUMSONG
	 * @param EPD_NNUMSONG  the value for CG.EP_PROJECTDETAIL.EPD_NNUMSONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NNUMSONG(BigDecimal EPD_NNUMSONG) {
		this.EPD_NNUMSONG = EPD_NNUMSONG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NPRICESONG
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NPRICESONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NPRICESONG() {
		return EPD_NPRICESONG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NPRICESONG
	 * @param EPD_NPRICESONG  the value for CG.EP_PROJECTDETAIL.EPD_NPRICESONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NPRICESONG(BigDecimal EPD_NPRICESONG) {
		this.EPD_NPRICESONG = EPD_NPRICESONG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NTOTALSONG
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NTOTALSONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NTOTALSONG() {
		return EPD_NTOTALSONG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NTOTALSONG
	 * @param EPD_NTOTALSONG  the value for CG.EP_PROJECTDETAIL.EPD_NTOTALSONG
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NTOTALSONG(BigDecimal EPD_NTOTALSONG) {
		this.EPD_NTOTALSONG = EPD_NTOTALSONG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NNUMJIAN
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NNUMJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NNUMJIAN() {
		return EPD_NNUMJIAN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NNUMJIAN
	 * @param EPD_NNUMJIAN  the value for CG.EP_PROJECTDETAIL.EPD_NNUMJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NNUMJIAN(BigDecimal EPD_NNUMJIAN) {
		this.EPD_NNUMJIAN = EPD_NNUMJIAN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NPRICEJIAN
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NPRICEJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NPRICEJIAN() {
		return EPD_NPRICEJIAN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NPRICEJIAN
	 * @param EPD_NPRICEJIAN  the value for CG.EP_PROJECTDETAIL.EPD_NPRICEJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NPRICEJIAN(BigDecimal EPD_NPRICEJIAN) {
		this.EPD_NPRICEJIAN = EPD_NPRICEJIAN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NTOTALJIAN
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NTOTALJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NTOTALJIAN() {
		return EPD_NTOTALJIAN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NTOTALJIAN
	 * @param EPD_NTOTALJIAN  the value for CG.EP_PROJECTDETAIL.EPD_NTOTALJIAN
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NTOTALJIAN(BigDecimal EPD_NTOTALJIAN) {
		this.EPD_NTOTALJIAN = EPD_NTOTALJIAN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NCANNOT
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NCANNOT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NCANNOT() {
		return EPD_NCANNOT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NCANNOT
	 * @param EPD_NCANNOT  the value for CG.EP_PROJECTDETAIL.EPD_NCANNOT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NCANNOT(BigDecimal EPD_NCANNOT) {
		this.EPD_NCANNOT = EPD_NCANNOT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SAPPROVENOTE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SAPPROVENOTE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SAPPROVENOTE() {
		return EPD_SAPPROVENOTE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SAPPROVENOTE
	 * @param EPD_SAPPROVENOTE  the value for CG.EP_PROJECTDETAIL.EPD_SAPPROVENOTE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SAPPROVENOTE(String EPD_SAPPROVENOTE) {
		this.EPD_SAPPROVENOTE = EPD_SAPPROVENOTE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SSTAT
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SSTAT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SSTAT() {
		return EPD_SSTAT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SSTAT
	 * @param EPD_SSTAT  the value for CG.EP_PROJECTDETAIL.EPD_SSTAT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SSTAT(String EPD_SSTAT) {
		this.EPD_SSTAT = EPD_SSTAT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SPURTYPE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SPURTYPE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SPURTYPE() {
		return EPD_SPURTYPE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SPURTYPE
	 * @param EPD_SPURTYPE  the value for CG.EP_PROJECTDETAIL.EPD_SPURTYPE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SPURTYPE(String EPD_SPURTYPE) {
		this.EPD_SPURTYPE = EPD_SPURTYPE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SISIMPORT
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SISIMPORT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SISIMPORT() {
		return EPD_SISIMPORT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SISIMPORT
	 * @param EPD_SISIMPORT  the value for CG.EP_PROJECTDETAIL.EPD_SISIMPORT
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SISIMPORT(String EPD_SISIMPORT) {
		this.EPD_SISIMPORT = EPD_SISIMPORT;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SISFREETAX
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SISFREETAX
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SISFREETAX() {
		return EPD_SISFREETAX;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SISFREETAX
	 * @param EPD_SISFREETAX  the value for CG.EP_PROJECTDETAIL.EPD_SISFREETAX
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SISFREETAX(String EPD_SISFREETAX) {
		this.EPD_SISFREETAX = EPD_SISFREETAX;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SJKFILE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SJKFILE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SJKFILE() {
		return EPD_SJKFILE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SJKFILE
	 * @param EPD_SJKFILE  the value for CG.EP_PROJECTDETAIL.EPD_SJKFILE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SJKFILE(String EPD_SJKFILE) {
		this.EPD_SJKFILE = EPD_SJKFILE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SMSFILE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SMSFILE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SMSFILE() {
		return EPD_SMSFILE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SMSFILE
	 * @param EPD_SMSFILE  the value for CG.EP_PROJECTDETAIL.EPD_SMSFILE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SMSFILE(String EPD_SMSFILE) {
		this.EPD_SMSFILE = EPD_SMSFILE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.PL_SPARA
	 * @return  the value of CG.EP_PROJECTDETAIL.PL_SPARA
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getPL_SPARA() {
		return PL_SPARA;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.PL_SPARA
	 * @param PL_SPARA  the value for CG.EP_PROJECTDETAIL.PL_SPARA
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setPL_SPARA(String PL_SPARA) {
		this.PL_SPARA = PL_SPARA;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.PL_SREMARK
	 * @return  the value of CG.EP_PROJECTDETAIL.PL_SREMARK
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getPL_SREMARK() {
		return PL_SREMARK;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.PL_SREMARK
	 * @param PL_SREMARK  the value for CG.EP_PROJECTDETAIL.PL_SREMARK
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setPL_SREMARK(String PL_SREMARK) {
		this.PL_SREMARK = PL_SREMARK;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.PL_SPAYTYPE
	 * @return  the value of CG.EP_PROJECTDETAIL.PL_SPAYTYPE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getPL_SPAYTYPE() {
		return PL_SPAYTYPE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.PL_SPAYTYPE
	 * @param PL_SPAYTYPE  the value for CG.EP_PROJECTDETAIL.PL_SPAYTYPE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setPL_SPAYTYPE(String PL_SPAYTYPE) {
		this.PL_SPAYTYPE = PL_SPAYTYPE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.PL_SBUYDATE
	 * @return  the value of CG.EP_PROJECTDETAIL.PL_SBUYDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getPL_SBUYDATE() {
		return PL_SBUYDATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.PL_SBUYDATE
	 * @param PL_SBUYDATE  the value for CG.EP_PROJECTDETAIL.PL_SBUYDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setPL_SBUYDATE(Date PL_SBUYDATE) {
		this.PL_SBUYDATE = PL_SBUYDATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SISDEL
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SISDEL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SISDEL() {
		return EPD_SISDEL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SISDEL
	 * @param EPD_SISDEL  the value for CG.EP_PROJECTDETAIL.EPD_SISDEL
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SISDEL(String EPD_SISDEL) {
		this.EPD_SISDEL = EPD_SISDEL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SISVALID
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SISVALID
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SISVALID() {
		return EPD_SISVALID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SISVALID
	 * @param EPD_SISVALID  the value for CG.EP_PROJECTDETAIL.EPD_SISVALID
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SISVALID(String EPD_SISVALID) {
		this.EPD_SISVALID = EPD_SISVALID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SREPLYBY
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SREPLYBY
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SREPLYBY() {
		return EPD_SREPLYBY;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SREPLYBY
	 * @param EPD_SREPLYBY  the value for CG.EP_PROJECTDETAIL.EPD_SREPLYBY
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SREPLYBY(String EPD_SREPLYBY) {
		this.EPD_SREPLYBY = EPD_SREPLYBY;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SREPLYDATE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SREPLYDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_SREPLYDATE() {
		return EPD_SREPLYDATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SREPLYDATE
	 * @param EPD_SREPLYDATE  the value for CG.EP_PROJECTDETAIL.EPD_SREPLYDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SREPLYDATE(Date EPD_SREPLYDATE) {
		this.EPD_SREPLYDATE = EPD_SREPLYDATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SALTERBY
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SALTERBY
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SALTERBY() {
		return EPD_SALTERBY;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SALTERBY
	 * @param EPD_SALTERBY  the value for CG.EP_PROJECTDETAIL.EPD_SALTERBY
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SALTERBY(String EPD_SALTERBY) {
		this.EPD_SALTERBY = EPD_SALTERBY;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SALTERDATE
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SALTERDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_SALTERDATE() {
		return EPD_SALTERDATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SALTERDATE
	 * @param EPD_SALTERDATE  the value for CG.EP_PROJECTDETAIL.EPD_SALTERDATE
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SALTERDATE(Date EPD_SALTERDATE) {
		this.EPD_SALTERDATE = EPD_SALTERDATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF1
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF1() {
		return EPD_SDEF1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF1
	 * @param EPD_SDEF1  the value for CG.EP_PROJECTDETAIL.EPD_SDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF1(String EPD_SDEF1) {
		this.EPD_SDEF1 = EPD_SDEF1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF2
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF2() {
		return EPD_SDEF2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF2
	 * @param EPD_SDEF2  the value for CG.EP_PROJECTDETAIL.EPD_SDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF2(String EPD_SDEF2) {
		this.EPD_SDEF2 = EPD_SDEF2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF3
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF3() {
		return EPD_SDEF3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF3
	 * @param EPD_SDEF3  the value for CG.EP_PROJECTDETAIL.EPD_SDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF3(String EPD_SDEF3) {
		this.EPD_SDEF3 = EPD_SDEF3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF4
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF4() {
		return EPD_SDEF4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF4
	 * @param EPD_SDEF4  the value for CG.EP_PROJECTDETAIL.EPD_SDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF4(String EPD_SDEF4) {
		this.EPD_SDEF4 = EPD_SDEF4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF5
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF5() {
		return EPD_SDEF5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF5
	 * @param EPD_SDEF5  the value for CG.EP_PROJECTDETAIL.EPD_SDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF5(String EPD_SDEF5) {
		this.EPD_SDEF5 = EPD_SDEF5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF6
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF6
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF6() {
		return EPD_SDEF6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF6
	 * @param EPD_SDEF6  the value for CG.EP_PROJECTDETAIL.EPD_SDEF6
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF6(String EPD_SDEF6) {
		this.EPD_SDEF6 = EPD_SDEF6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF7
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF7
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF7() {
		return EPD_SDEF7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF7
	 * @param EPD_SDEF7  the value for CG.EP_PROJECTDETAIL.EPD_SDEF7
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF7(String EPD_SDEF7) {
		this.EPD_SDEF7 = EPD_SDEF7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF8
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF8
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF8() {
		return EPD_SDEF8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF8
	 * @param EPD_SDEF8  the value for CG.EP_PROJECTDETAIL.EPD_SDEF8
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF8(String EPD_SDEF8) {
		this.EPD_SDEF8 = EPD_SDEF8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF9
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF9
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF9() {
		return EPD_SDEF9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF9
	 * @param EPD_SDEF9  the value for CG.EP_PROJECTDETAIL.EPD_SDEF9
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF9(String EPD_SDEF9) {
		this.EPD_SDEF9 = EPD_SDEF9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF10
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF10
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF10() {
		return EPD_SDEF10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF10
	 * @param EPD_SDEF10  the value for CG.EP_PROJECTDETAIL.EPD_SDEF10
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF10(String EPD_SDEF10) {
		this.EPD_SDEF10 = EPD_SDEF10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF11
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF11
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF11() {
		return EPD_SDEF11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF11
	 * @param EPD_SDEF11  the value for CG.EP_PROJECTDETAIL.EPD_SDEF11
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF11(String EPD_SDEF11) {
		this.EPD_SDEF11 = EPD_SDEF11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF12
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF12
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF12() {
		return EPD_SDEF12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF12
	 * @param EPD_SDEF12  the value for CG.EP_PROJECTDETAIL.EPD_SDEF12
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF12(String EPD_SDEF12) {
		this.EPD_SDEF12 = EPD_SDEF12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF13
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF13
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF13() {
		return EPD_SDEF13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF13
	 * @param EPD_SDEF13  the value for CG.EP_PROJECTDETAIL.EPD_SDEF13
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF13(String EPD_SDEF13) {
		this.EPD_SDEF13 = EPD_SDEF13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF14
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF14
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF14() {
		return EPD_SDEF14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF14
	 * @param EPD_SDEF14  the value for CG.EP_PROJECTDETAIL.EPD_SDEF14
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF14(String EPD_SDEF14) {
		this.EPD_SDEF14 = EPD_SDEF14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF15
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF15
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF15() {
		return EPD_SDEF15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF15
	 * @param EPD_SDEF15  the value for CG.EP_PROJECTDETAIL.EPD_SDEF15
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF15(String EPD_SDEF15) {
		this.EPD_SDEF15 = EPD_SDEF15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF16
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF16
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF16() {
		return EPD_SDEF16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF16
	 * @param EPD_SDEF16  the value for CG.EP_PROJECTDETAIL.EPD_SDEF16
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF16(String EPD_SDEF16) {
		this.EPD_SDEF16 = EPD_SDEF16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF17
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF17
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF17() {
		return EPD_SDEF17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF17
	 * @param EPD_SDEF17  the value for CG.EP_PROJECTDETAIL.EPD_SDEF17
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF17(String EPD_SDEF17) {
		this.EPD_SDEF17 = EPD_SDEF17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF18
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF18
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF18() {
		return EPD_SDEF18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF18
	 * @param EPD_SDEF18  the value for CG.EP_PROJECTDETAIL.EPD_SDEF18
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF18(String EPD_SDEF18) {
		this.EPD_SDEF18 = EPD_SDEF18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF19
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF19
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF19() {
		return EPD_SDEF19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF19
	 * @param EPD_SDEF19  the value for CG.EP_PROJECTDETAIL.EPD_SDEF19
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF19(String EPD_SDEF19) {
		this.EPD_SDEF19 = EPD_SDEF19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF20
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_SDEF20
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public String getEPD_SDEF20() {
		return EPD_SDEF20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_SDEF20
	 * @param EPD_SDEF20  the value for CG.EP_PROJECTDETAIL.EPD_SDEF20
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_SDEF20(String EPD_SDEF20) {
		this.EPD_SDEF20 = EPD_SDEF20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF1
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF1() {
		return EPD_NDEF1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF1
	 * @param EPD_NDEF1  the value for CG.EP_PROJECTDETAIL.EPD_NDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF1(BigDecimal EPD_NDEF1) {
		this.EPD_NDEF1 = EPD_NDEF1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF2
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF2() {
		return EPD_NDEF2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF2
	 * @param EPD_NDEF2  the value for CG.EP_PROJECTDETAIL.EPD_NDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF2(BigDecimal EPD_NDEF2) {
		this.EPD_NDEF2 = EPD_NDEF2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF3
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF3() {
		return EPD_NDEF3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF3
	 * @param EPD_NDEF3  the value for CG.EP_PROJECTDETAIL.EPD_NDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF3(BigDecimal EPD_NDEF3) {
		this.EPD_NDEF3 = EPD_NDEF3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF4
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF4() {
		return EPD_NDEF4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF4
	 * @param EPD_NDEF4  the value for CG.EP_PROJECTDETAIL.EPD_NDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF4(BigDecimal EPD_NDEF4) {
		this.EPD_NDEF4 = EPD_NDEF4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF5
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF5() {
		return EPD_NDEF5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF5
	 * @param EPD_NDEF5  the value for CG.EP_PROJECTDETAIL.EPD_NDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF5(BigDecimal EPD_NDEF5) {
		this.EPD_NDEF5 = EPD_NDEF5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF6
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF6
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF6() {
		return EPD_NDEF6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF6
	 * @param EPD_NDEF6  the value for CG.EP_PROJECTDETAIL.EPD_NDEF6
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF6(BigDecimal EPD_NDEF6) {
		this.EPD_NDEF6 = EPD_NDEF6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF7
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF7
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF7() {
		return EPD_NDEF7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF7
	 * @param EPD_NDEF7  the value for CG.EP_PROJECTDETAIL.EPD_NDEF7
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF7(BigDecimal EPD_NDEF7) {
		this.EPD_NDEF7 = EPD_NDEF7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF8
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF8
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF8() {
		return EPD_NDEF8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF8
	 * @param EPD_NDEF8  the value for CG.EP_PROJECTDETAIL.EPD_NDEF8
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF8(BigDecimal EPD_NDEF8) {
		this.EPD_NDEF8 = EPD_NDEF8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF9
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF9
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF9() {
		return EPD_NDEF9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF9
	 * @param EPD_NDEF9  the value for CG.EP_PROJECTDETAIL.EPD_NDEF9
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF9(BigDecimal EPD_NDEF9) {
		this.EPD_NDEF9 = EPD_NDEF9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF10
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_NDEF10
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public BigDecimal getEPD_NDEF10() {
		return EPD_NDEF10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_NDEF10
	 * @param EPD_NDEF10  the value for CG.EP_PROJECTDETAIL.EPD_NDEF10
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_NDEF10(BigDecimal EPD_NDEF10) {
		this.EPD_NDEF10 = EPD_NDEF10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF1
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_DDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_DDEF1() {
		return EPD_DDEF1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF1
	 * @param EPD_DDEF1  the value for CG.EP_PROJECTDETAIL.EPD_DDEF1
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_DDEF1(Date EPD_DDEF1) {
		this.EPD_DDEF1 = EPD_DDEF1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF2
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_DDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_DDEF2() {
		return EPD_DDEF2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF2
	 * @param EPD_DDEF2  the value for CG.EP_PROJECTDETAIL.EPD_DDEF2
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_DDEF2(Date EPD_DDEF2) {
		this.EPD_DDEF2 = EPD_DDEF2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF3
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_DDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_DDEF3() {
		return EPD_DDEF3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF3
	 * @param EPD_DDEF3  the value for CG.EP_PROJECTDETAIL.EPD_DDEF3
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_DDEF3(Date EPD_DDEF3) {
		this.EPD_DDEF3 = EPD_DDEF3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF4
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_DDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_DDEF4() {
		return EPD_DDEF4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF4
	 * @param EPD_DDEF4  the value for CG.EP_PROJECTDETAIL.EPD_DDEF4
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_DDEF4(Date EPD_DDEF4) {
		this.EPD_DDEF4 = EPD_DDEF4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF5
	 * @return  the value of CG.EP_PROJECTDETAIL.EPD_DDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public Date getEPD_DDEF5() {
		return EPD_DDEF5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CG.EP_PROJECTDETAIL.EPD_DDEF5
	 * @param EPD_DDEF5  the value for CG.EP_PROJECTDETAIL.EPD_DDEF5
	 * @ibatorgenerated  Tue Mar 18 17:13:11 CST 2014
	 */
	public void setEPD_DDEF5(Date EPD_DDEF5) {
		this.EPD_DDEF5 = EPD_DDEF5;
	}

	public EpProjectDetail toVO() {
		try {

			EpProjectDetail vo = new EpProjectDetail();
			EpProjectDetailForm.class.getFields();
			for (Field field : EpProjectDetail.class.getDeclaredFields()) {
				Field sField = EpProjectDetailForm.class.getDeclaredField(field.getName());
				if (sField != null) {
					sField.setAccessible(true);
					field.setAccessible(true);
					Object value = sField.get(this);
					field.set(vo, value);
				}

			}
			return vo;
		} catch (Exception e) {
			throw new RuntimeException(e);
		}

	}	

}