package com.rc.project.form;

import java.math.BigDecimal;
import java.util.Date;

public class EpProjectForm {
	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SNO;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SID
     *
     * @return the value of CG.EP_PROJECT.EP_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SID() {
        return EP_SID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SID
     *
     * @param EP_SID the value for CG.EP_PROJECT.EP_SID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SID(String EP_SID) {
        this.EP_SID = EP_SID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SNO
     *
     * @return the value of CG.EP_PROJECT.EP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SNO() {
        return EP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SNO
     *
     * @param EP_SNO the value for CG.EP_PROJECT.EP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SNO(String EP_SNO) {
        this.EP_SNO = EP_SNO;
    }
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.RP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RP_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SYEAR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SNAMEXIAO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SNAMEXIAO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SMONEY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_SMONEY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SISZC
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SISZC;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String UD_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SPERDEPARTNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SPERDEPARTNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EMP_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SPERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SPERSON;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EP_SDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_NDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal EP_NDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_DDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_DDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_DDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_DDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_DDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_DDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_DDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_DDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.EP_PROJECT.EP_DDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date EP_DDEF5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.RP_SNO
     *
     * @return the value of CG.EP_PROJECT.RP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRP_SNO() {
        return RP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.RP_SNO
     *
     * @param RP_SNO the value for CG.EP_PROJECT.RP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRP_SNO(String RP_SNO) {
        this.RP_SNO = RP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SYEAR
     *
     * @return the value of CG.EP_PROJECT.EP_SYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SYEAR() {
        return EP_SYEAR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SYEAR
     *
     * @param EP_SYEAR the value for CG.EP_PROJECT.EP_SYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SYEAR(String EP_SYEAR) {
        this.EP_SYEAR = EP_SYEAR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SNAME
     *
     * @return the value of CG.EP_PROJECT.EP_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SNAME() {
        return EP_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SNAME
     *
     * @param EP_SNAME the value for CG.EP_PROJECT.EP_SNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SNAME(String EP_SNAME) {
        this.EP_SNAME = EP_SNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SNAMEXIAO
     *
     * @return the value of CG.EP_PROJECT.EP_SNAMEXIAO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SNAMEXIAO() {
        return EP_SNAMEXIAO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SNAMEXIAO
     *
     * @param EP_SNAMEXIAO the value for CG.EP_PROJECT.EP_SNAMEXIAO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SNAMEXIAO(String EP_SNAMEXIAO) {
        this.EP_SNAMEXIAO = EP_SNAMEXIAO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SMONEY
     *
     * @return the value of CG.EP_PROJECT.EP_SMONEY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_SMONEY() {
        return EP_SMONEY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SMONEY
     *
     * @param EP_SMONEY the value for CG.EP_PROJECT.EP_SMONEY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SMONEY(BigDecimal EP_SMONEY) {
        this.EP_SMONEY = EP_SMONEY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SISZC
     *
     * @return the value of CG.EP_PROJECT.EP_SISZC
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SISZC() {
        return EP_SISZC;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SISZC
     *
     * @param EP_SISZC the value for CG.EP_PROJECT.EP_SISZC
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SISZC(String EP_SISZC) {
        this.EP_SISZC = EP_SISZC;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.UD_SNO
     *
     * @return the value of CG.EP_PROJECT.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getUD_SNO() {
        return UD_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.UD_SNO
     *
     * @param UD_SNO the value for CG.EP_PROJECT.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setUD_SNO(String UD_SNO) {
        this.UD_SNO = UD_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SPERDEPARTNAME
     *
     * @return the value of CG.EP_PROJECT.EP_SPERDEPARTNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SPERDEPARTNAME() {
        return EP_SPERDEPARTNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SPERDEPARTNAME
     *
     * @param EP_SPERDEPARTNAME the value for CG.EP_PROJECT.EP_SPERDEPARTNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SPERDEPARTNAME(String EP_SPERDEPARTNAME) {
        this.EP_SPERDEPARTNAME = EP_SPERDEPARTNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EMP_SNO
     *
     * @return the value of CG.EP_PROJECT.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEMP_SNO() {
        return EMP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EMP_SNO
     *
     * @param EMP_SNO the value for CG.EP_PROJECT.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEMP_SNO(String EMP_SNO) {
        this.EMP_SNO = EMP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SPERSON
     *
     * @return the value of CG.EP_PROJECT.EP_SPERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SPERSON() {
        return EP_SPERSON;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SPERSON
     *
     * @param EP_SPERSON the value for CG.EP_PROJECT.EP_SPERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SPERSON(String EP_SPERSON) {
        this.EP_SPERSON = EP_SPERSON;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SISDEL
     *
     * @return the value of CG.EP_PROJECT.EP_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SISDEL() {
        return EP_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SISDEL
     *
     * @param EP_SISDEL the value for CG.EP_PROJECT.EP_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SISDEL(String EP_SISDEL) {
        this.EP_SISDEL = EP_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SISVALID
     *
     * @return the value of CG.EP_PROJECT.EP_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SISVALID() {
        return EP_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SISVALID
     *
     * @param EP_SISVALID the value for CG.EP_PROJECT.EP_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SISVALID(String EP_SISVALID) {
        this.EP_SISVALID = EP_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SREPLYBY
     *
     * @return the value of CG.EP_PROJECT.EP_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SREPLYBY() {
        return EP_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SREPLYBY
     *
     * @param EP_SREPLYBY the value for CG.EP_PROJECT.EP_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SREPLYBY(String EP_SREPLYBY) {
        this.EP_SREPLYBY = EP_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SREPLYDATE
     *
     * @return the value of CG.EP_PROJECT.EP_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_SREPLYDATE() {
        return EP_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SREPLYDATE
     *
     * @param EP_SREPLYDATE the value for CG.EP_PROJECT.EP_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SREPLYDATE(Date EP_SREPLYDATE) {
        this.EP_SREPLYDATE = EP_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SALTERBY
     *
     * @return the value of CG.EP_PROJECT.EP_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SALTERBY() {
        return EP_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SALTERBY
     *
     * @param EP_SALTERBY the value for CG.EP_PROJECT.EP_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SALTERBY(String EP_SALTERBY) {
        this.EP_SALTERBY = EP_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SALTERDATE
     *
     * @return the value of CG.EP_PROJECT.EP_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_SALTERDATE() {
        return EP_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SALTERDATE
     *
     * @param EP_SALTERDATE the value for CG.EP_PROJECT.EP_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SALTERDATE(Date EP_SALTERDATE) {
        this.EP_SALTERDATE = EP_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF1
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF1() {
        return EP_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF1
     *
     * @param EP_SDEF1 the value for CG.EP_PROJECT.EP_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF1(String EP_SDEF1) {
        this.EP_SDEF1 = EP_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF2
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF2() {
        return EP_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF2
     *
     * @param EP_SDEF2 the value for CG.EP_PROJECT.EP_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF2(String EP_SDEF2) {
        this.EP_SDEF2 = EP_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF3
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF3() {
        return EP_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF3
     *
     * @param EP_SDEF3 the value for CG.EP_PROJECT.EP_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF3(String EP_SDEF3) {
        this.EP_SDEF3 = EP_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF4
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF4() {
        return EP_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF4
     *
     * @param EP_SDEF4 the value for CG.EP_PROJECT.EP_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF4(String EP_SDEF4) {
        this.EP_SDEF4 = EP_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF5
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF5() {
        return EP_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF5
     *
     * @param EP_SDEF5 the value for CG.EP_PROJECT.EP_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF5(String EP_SDEF5) {
        this.EP_SDEF5 = EP_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF6
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF6() {
        return EP_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF6
     *
     * @param EP_SDEF6 the value for CG.EP_PROJECT.EP_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF6(String EP_SDEF6) {
        this.EP_SDEF6 = EP_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF7
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF7() {
        return EP_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF7
     *
     * @param EP_SDEF7 the value for CG.EP_PROJECT.EP_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF7(String EP_SDEF7) {
        this.EP_SDEF7 = EP_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF8
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF8() {
        return EP_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF8
     *
     * @param EP_SDEF8 the value for CG.EP_PROJECT.EP_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF8(String EP_SDEF8) {
        this.EP_SDEF8 = EP_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF9
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF9() {
        return EP_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF9
     *
     * @param EP_SDEF9 the value for CG.EP_PROJECT.EP_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF9(String EP_SDEF9) {
        this.EP_SDEF9 = EP_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF10
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF10() {
        return EP_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF10
     *
     * @param EP_SDEF10 the value for CG.EP_PROJECT.EP_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF10(String EP_SDEF10) {
        this.EP_SDEF10 = EP_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF11
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF11() {
        return EP_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF11
     *
     * @param EP_SDEF11 the value for CG.EP_PROJECT.EP_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF11(String EP_SDEF11) {
        this.EP_SDEF11 = EP_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF12
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF12() {
        return EP_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF12
     *
     * @param EP_SDEF12 the value for CG.EP_PROJECT.EP_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF12(String EP_SDEF12) {
        this.EP_SDEF12 = EP_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF13
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF13() {
        return EP_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF13
     *
     * @param EP_SDEF13 the value for CG.EP_PROJECT.EP_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF13(String EP_SDEF13) {
        this.EP_SDEF13 = EP_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF14
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF14() {
        return EP_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF14
     *
     * @param EP_SDEF14 the value for CG.EP_PROJECT.EP_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF14(String EP_SDEF14) {
        this.EP_SDEF14 = EP_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF15
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF15() {
        return EP_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF15
     *
     * @param EP_SDEF15 the value for CG.EP_PROJECT.EP_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF15(String EP_SDEF15) {
        this.EP_SDEF15 = EP_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF16
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF16() {
        return EP_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF16
     *
     * @param EP_SDEF16 the value for CG.EP_PROJECT.EP_SDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF16(String EP_SDEF16) {
        this.EP_SDEF16 = EP_SDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF17
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF17() {
        return EP_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF17
     *
     * @param EP_SDEF17 the value for CG.EP_PROJECT.EP_SDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF17(String EP_SDEF17) {
        this.EP_SDEF17 = EP_SDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF18
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF18() {
        return EP_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF18
     *
     * @param EP_SDEF18 the value for CG.EP_PROJECT.EP_SDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF18(String EP_SDEF18) {
        this.EP_SDEF18 = EP_SDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF19
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF19() {
        return EP_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF19
     *
     * @param EP_SDEF19 the value for CG.EP_PROJECT.EP_SDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF19(String EP_SDEF19) {
        this.EP_SDEF19 = EP_SDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_SDEF20
     *
     * @return the value of CG.EP_PROJECT.EP_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEP_SDEF20() {
        return EP_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_SDEF20
     *
     * @param EP_SDEF20 the value for CG.EP_PROJECT.EP_SDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_SDEF20(String EP_SDEF20) {
        this.EP_SDEF20 = EP_SDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF1
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF1() {
        return EP_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF1
     *
     * @param EP_NDEF1 the value for CG.EP_PROJECT.EP_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF1(BigDecimal EP_NDEF1) {
        this.EP_NDEF1 = EP_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF2
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF2() {
        return EP_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF2
     *
     * @param EP_NDEF2 the value for CG.EP_PROJECT.EP_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF2(BigDecimal EP_NDEF2) {
        this.EP_NDEF2 = EP_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF3
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF3() {
        return EP_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF3
     *
     * @param EP_NDEF3 the value for CG.EP_PROJECT.EP_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF3(BigDecimal EP_NDEF3) {
        this.EP_NDEF3 = EP_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF4
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF4() {
        return EP_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF4
     *
     * @param EP_NDEF4 the value for CG.EP_PROJECT.EP_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF4(BigDecimal EP_NDEF4) {
        this.EP_NDEF4 = EP_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF5
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF5() {
        return EP_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF5
     *
     * @param EP_NDEF5 the value for CG.EP_PROJECT.EP_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF5(BigDecimal EP_NDEF5) {
        this.EP_NDEF5 = EP_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF6
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF6() {
        return EP_NDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF6
     *
     * @param EP_NDEF6 the value for CG.EP_PROJECT.EP_NDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF6(BigDecimal EP_NDEF6) {
        this.EP_NDEF6 = EP_NDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF7
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF7() {
        return EP_NDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF7
     *
     * @param EP_NDEF7 the value for CG.EP_PROJECT.EP_NDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF7(BigDecimal EP_NDEF7) {
        this.EP_NDEF7 = EP_NDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF8
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF8() {
        return EP_NDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF8
     *
     * @param EP_NDEF8 the value for CG.EP_PROJECT.EP_NDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF8(BigDecimal EP_NDEF8) {
        this.EP_NDEF8 = EP_NDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF9
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF9() {
        return EP_NDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF9
     *
     * @param EP_NDEF9 the value for CG.EP_PROJECT.EP_NDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF9(BigDecimal EP_NDEF9) {
        this.EP_NDEF9 = EP_NDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_NDEF10
     *
     * @return the value of CG.EP_PROJECT.EP_NDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getEP_NDEF10() {
        return EP_NDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_NDEF10
     *
     * @param EP_NDEF10 the value for CG.EP_PROJECT.EP_NDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_NDEF10(BigDecimal EP_NDEF10) {
        this.EP_NDEF10 = EP_NDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_DDEF1
     *
     * @return the value of CG.EP_PROJECT.EP_DDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_DDEF1() {
        return EP_DDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_DDEF1
     *
     * @param EP_DDEF1 the value for CG.EP_PROJECT.EP_DDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_DDEF1(Date EP_DDEF1) {
        this.EP_DDEF1 = EP_DDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_DDEF2
     *
     * @return the value of CG.EP_PROJECT.EP_DDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_DDEF2() {
        return EP_DDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_DDEF2
     *
     * @param EP_DDEF2 the value for CG.EP_PROJECT.EP_DDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_DDEF2(Date EP_DDEF2) {
        this.EP_DDEF2 = EP_DDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_DDEF3
     *
     * @return the value of CG.EP_PROJECT.EP_DDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_DDEF3() {
        return EP_DDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_DDEF3
     *
     * @param EP_DDEF3 the value for CG.EP_PROJECT.EP_DDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_DDEF3(Date EP_DDEF3) {
        this.EP_DDEF3 = EP_DDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_DDEF4
     *
     * @return the value of CG.EP_PROJECT.EP_DDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_DDEF4() {
        return EP_DDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_DDEF4
     *
     * @param EP_DDEF4 the value for CG.EP_PROJECT.EP_DDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_DDEF4(Date EP_DDEF4) {
        this.EP_DDEF4 = EP_DDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.EP_PROJECT.EP_DDEF5
     *
     * @return the value of CG.EP_PROJECT.EP_DDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getEP_DDEF5() {
        return EP_DDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.EP_PROJECT.EP_DDEF5
     *
     * @param EP_DDEF5 the value for CG.EP_PROJECT.EP_DDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEP_DDEF5(Date EP_DDEF5) {
        this.EP_DDEF5 = EP_DDEF5;
    }
}