package com.rc.project.form;

import java.math.BigDecimal;
import java.util.Date;

public class RpReportBeginForm {
	
	/**
	 * 文件路径
	 */
	private String filePath;
	
	/**
	 * 文件名称
	 */
	private String fileName;
	
    /**
     * 
     */
    private String pageSQLA;//分页前段
	
	/**
	 * 
	 */
	private String pageSQLB;//分页后段
	
	/**
	 * rpbSyear 年份
	 */
	private String searchA;
	/**
	 * udSno 学校
	 */
	private String searchB1;
	/**
	 * udSno1 院系
	 */
	private String searchB2;
	/**
	 * rpbSprojectname 项目名称
	 */
	private String searchC;
	/**
	 * empSno 项目负责人
	 */
	private String searchD;
	/**
	 * rpbSreplyDate 导入时间开始
	 */
	private String searchE;
	/**
	 * rpbSreplyDate 导入结束开始
	 */
	private String searchF;
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NNUM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String UD_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.UD_SNO1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String UD_SNO1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SREPORTUNITNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SREPORTUNITNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SPROJECTNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SPROJECTNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SYEAR;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String EMP_SNO;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SPERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SPERSON;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SPROTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SPROTYPE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SREPORTTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_SREPORTTOTAL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SSUGGESTTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_SSUGGESTTOTAL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SLEVEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SLEVEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SMEM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SMEM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SISDEL;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SISVALID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SREPLYBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_SREPLYDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SALTERBY;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_SALTERDATE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private String RPB_SDEF14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_SDEF15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_DDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_DDEF16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_DDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_DDEF17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_DDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_DDEF18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_DDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_DDEF19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_DDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Date RPB_DDEF20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private Long RPB_NDEF1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CG.RP_REPORTBEGIN.RPB_NDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    private BigDecimal RPB_NDEF11;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SNO
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SNO() {
        return RPB_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SNO
     *
     * @param RPB_SNO the value for CG.RP_REPORTBEGIN.RPB_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SNO(String RPB_SNO) {
        this.RPB_SNO = RPB_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NNUM
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NNUM() {
        return RPB_NNUM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NNUM
     *
     * @param RPB_NNUM the value for CG.RP_REPORTBEGIN.RPB_NNUM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NNUM(BigDecimal RPB_NNUM) {
        this.RPB_NNUM = RPB_NNUM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.UD_SNO
     *
     * @return the value of CG.RP_REPORTBEGIN.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getUD_SNO() {
        return UD_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.UD_SNO
     *
     * @param UD_SNO the value for CG.RP_REPORTBEGIN.UD_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setUD_SNO(String UD_SNO) {
        this.UD_SNO = UD_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.UD_SNO1
     *
     * @return the value of CG.RP_REPORTBEGIN.UD_SNO1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getUD_SNO1() {
        return UD_SNO1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.UD_SNO1
     *
     * @param UD_SNO1 the value for CG.RP_REPORTBEGIN.UD_SNO1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setUD_SNO1(String UD_SNO1) {
        this.UD_SNO1 = UD_SNO1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SREPORTUNITNAME
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SREPORTUNITNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SREPORTUNITNAME() {
        return RPB_SREPORTUNITNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SREPORTUNITNAME
     *
     * @param RPB_SREPORTUNITNAME the value for CG.RP_REPORTBEGIN.RPB_SREPORTUNITNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SREPORTUNITNAME(String RPB_SREPORTUNITNAME) {
        this.RPB_SREPORTUNITNAME = RPB_SREPORTUNITNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SPROJECTNAME
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SPROJECTNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SPROJECTNAME() {
        return RPB_SPROJECTNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SPROJECTNAME
     *
     * @param RPB_SPROJECTNAME the value for CG.RP_REPORTBEGIN.RPB_SPROJECTNAME
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SPROJECTNAME(String RPB_SPROJECTNAME) {
        this.RPB_SPROJECTNAME = RPB_SPROJECTNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SYEAR
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SYEAR() {
        return RPB_SYEAR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SYEAR
     *
     * @param RPB_SYEAR the value for CG.RP_REPORTBEGIN.RPB_SYEAR
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SYEAR(String RPB_SYEAR) {
        this.RPB_SYEAR = RPB_SYEAR;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.EMP_SNO
     *
     * @return the value of CG.RP_REPORTBEGIN.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getEMP_SNO() {
        return EMP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.EMP_SNO
     *
     * @param EMP_SNO the value for CG.RP_REPORTBEGIN.EMP_SNO
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setEMP_SNO(String EMP_SNO) {
        this.EMP_SNO = EMP_SNO;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SPERSON
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SPERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SPERSON() {
        return RPB_SPERSON;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SPERSON
     *
     * @param RPB_SPERSON the value for CG.RP_REPORTBEGIN.RPB_SPERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SPERSON(String RPB_SPERSON) {
        this.RPB_SPERSON = RPB_SPERSON;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SPROTYPE
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SPROTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SPROTYPE() {
        return RPB_SPROTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SPROTYPE
     *
     * @param RPB_SPROTYPE the value for CG.RP_REPORTBEGIN.RPB_SPROTYPE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SPROTYPE(String RPB_SPROTYPE) {
        this.RPB_SPROTYPE = RPB_SPROTYPE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SREPORTTOTAL
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SREPORTTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_SREPORTTOTAL() {
        return RPB_SREPORTTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SREPORTTOTAL
     *
     * @param RPB_SREPORTTOTAL the value for CG.RP_REPORTBEGIN.RPB_SREPORTTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SREPORTTOTAL(BigDecimal RPB_SREPORTTOTAL) {
        this.RPB_SREPORTTOTAL = RPB_SREPORTTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SSUGGESTTOTAL
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SSUGGESTTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_SSUGGESTTOTAL() {
        return RPB_SSUGGESTTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SSUGGESTTOTAL
     *
     * @param RPB_SSUGGESTTOTAL the value for CG.RP_REPORTBEGIN.RPB_SSUGGESTTOTAL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SSUGGESTTOTAL(BigDecimal RPB_SSUGGESTTOTAL) {
        this.RPB_SSUGGESTTOTAL = RPB_SSUGGESTTOTAL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SLEVEL
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SLEVEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SLEVEL() {
        return RPB_SLEVEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SLEVEL
     *
     * @param RPB_SLEVEL the value for CG.RP_REPORTBEGIN.RPB_SLEVEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SLEVEL(String RPB_SLEVEL) {
        this.RPB_SLEVEL = RPB_SLEVEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SMEM
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SMEM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SMEM() {
        return RPB_SMEM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SMEM
     *
     * @param RPB_SMEM the value for CG.RP_REPORTBEGIN.RPB_SMEM
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SMEM(String RPB_SMEM) {
        this.RPB_SMEM = RPB_SMEM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SISDEL
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SISDEL() {
        return RPB_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SISDEL
     *
     * @param RPB_SISDEL the value for CG.RP_REPORTBEGIN.RPB_SISDEL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SISDEL(String RPB_SISDEL) {
        this.RPB_SISDEL = RPB_SISDEL;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SISVALID
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SISVALID() {
        return RPB_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SISVALID
     *
     * @param RPB_SISVALID the value for CG.RP_REPORTBEGIN.RPB_SISVALID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SISVALID(String RPB_SISVALID) {
        this.RPB_SISVALID = RPB_SISVALID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SREPLYBY
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SREPLYBY() {
        return RPB_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SREPLYBY
     *
     * @param RPB_SREPLYBY the value for CG.RP_REPORTBEGIN.RPB_SREPLYBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SREPLYBY(String RPB_SREPLYBY) {
        this.RPB_SREPLYBY = RPB_SREPLYBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SREPLYDATE
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_SREPLYDATE() {
        return RPB_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SREPLYDATE
     *
     * @param RPB_SREPLYDATE the value for CG.RP_REPORTBEGIN.RPB_SREPLYDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SREPLYDATE(Date RPB_SREPLYDATE) {
        this.RPB_SREPLYDATE = RPB_SREPLYDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SALTERBY
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SALTERBY() {
        return RPB_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SALTERBY
     *
     * @param RPB_SALTERBY the value for CG.RP_REPORTBEGIN.RPB_SALTERBY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SALTERBY(String RPB_SALTERBY) {
        this.RPB_SALTERBY = RPB_SALTERBY;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SALTERDATE
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_SALTERDATE() {
        return RPB_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SALTERDATE
     *
     * @param RPB_SALTERDATE the value for CG.RP_REPORTBEGIN.RPB_SALTERDATE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SALTERDATE(Date RPB_SALTERDATE) {
        this.RPB_SALTERDATE = RPB_SALTERDATE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF1
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF1() {
        return RPB_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF1
     *
     * @param RPB_SDEF1 the value for CG.RP_REPORTBEGIN.RPB_SDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF1(String RPB_SDEF1) {
        this.RPB_SDEF1 = RPB_SDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF2
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF2() {
        return RPB_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF2
     *
     * @param RPB_SDEF2 the value for CG.RP_REPORTBEGIN.RPB_SDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF2(String RPB_SDEF2) {
        this.RPB_SDEF2 = RPB_SDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF3
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF3() {
        return RPB_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF3
     *
     * @param RPB_SDEF3 the value for CG.RP_REPORTBEGIN.RPB_SDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF3(String RPB_SDEF3) {
        this.RPB_SDEF3 = RPB_SDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF4
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF4() {
        return RPB_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF4
     *
     * @param RPB_SDEF4 the value for CG.RP_REPORTBEGIN.RPB_SDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF4(String RPB_SDEF4) {
        this.RPB_SDEF4 = RPB_SDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF5
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF5() {
        return RPB_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF5
     *
     * @param RPB_SDEF5 the value for CG.RP_REPORTBEGIN.RPB_SDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF5(String RPB_SDEF5) {
        this.RPB_SDEF5 = RPB_SDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF6
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF6() {
        return RPB_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF6
     *
     * @param RPB_SDEF6 the value for CG.RP_REPORTBEGIN.RPB_SDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF6(String RPB_SDEF6) {
        this.RPB_SDEF6 = RPB_SDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF7
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF7() {
        return RPB_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF7
     *
     * @param RPB_SDEF7 the value for CG.RP_REPORTBEGIN.RPB_SDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF7(String RPB_SDEF7) {
        this.RPB_SDEF7 = RPB_SDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF8
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF8() {
        return RPB_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF8
     *
     * @param RPB_SDEF8 the value for CG.RP_REPORTBEGIN.RPB_SDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF8(String RPB_SDEF8) {
        this.RPB_SDEF8 = RPB_SDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF9
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF9() {
        return RPB_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF9
     *
     * @param RPB_SDEF9 the value for CG.RP_REPORTBEGIN.RPB_SDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF9(String RPB_SDEF9) {
        this.RPB_SDEF9 = RPB_SDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF10
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF10() {
        return RPB_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF10
     *
     * @param RPB_SDEF10 the value for CG.RP_REPORTBEGIN.RPB_SDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF10(String RPB_SDEF10) {
        this.RPB_SDEF10 = RPB_SDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF11
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF11() {
        return RPB_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF11
     *
     * @param RPB_SDEF11 the value for CG.RP_REPORTBEGIN.RPB_SDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF11(String RPB_SDEF11) {
        this.RPB_SDEF11 = RPB_SDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF12
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF12() {
        return RPB_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF12
     *
     * @param RPB_SDEF12 the value for CG.RP_REPORTBEGIN.RPB_SDEF12
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF12(String RPB_SDEF12) {
        this.RPB_SDEF12 = RPB_SDEF12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF13
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF13() {
        return RPB_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF13
     *
     * @param RPB_SDEF13 the value for CG.RP_REPORTBEGIN.RPB_SDEF13
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF13(String RPB_SDEF13) {
        this.RPB_SDEF13 = RPB_SDEF13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF14
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public String getRPB_SDEF14() {
        return RPB_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF14
     *
     * @param RPB_SDEF14 the value for CG.RP_REPORTBEGIN.RPB_SDEF14
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF14(String RPB_SDEF14) {
        this.RPB_SDEF14 = RPB_SDEF14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF15
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_SDEF15() {
        return RPB_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_SDEF15
     *
     * @param RPB_SDEF15 the value for CG.RP_REPORTBEGIN.RPB_SDEF15
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_SDEF15(BigDecimal RPB_SDEF15) {
        this.RPB_SDEF15 = RPB_SDEF15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF16
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_DDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_DDEF16() {
        return RPB_DDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF16
     *
     * @param RPB_DDEF16 the value for CG.RP_REPORTBEGIN.RPB_DDEF16
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_DDEF16(Date RPB_DDEF16) {
        this.RPB_DDEF16 = RPB_DDEF16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF17
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_DDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_DDEF17() {
        return RPB_DDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF17
     *
     * @param RPB_DDEF17 the value for CG.RP_REPORTBEGIN.RPB_DDEF17
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_DDEF17(Date RPB_DDEF17) {
        this.RPB_DDEF17 = RPB_DDEF17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF18
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_DDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_DDEF18() {
        return RPB_DDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF18
     *
     * @param RPB_DDEF18 the value for CG.RP_REPORTBEGIN.RPB_DDEF18
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_DDEF18(Date RPB_DDEF18) {
        this.RPB_DDEF18 = RPB_DDEF18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF19
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_DDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_DDEF19() {
        return RPB_DDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF19
     *
     * @param RPB_DDEF19 the value for CG.RP_REPORTBEGIN.RPB_DDEF19
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_DDEF19(Date RPB_DDEF19) {
        this.RPB_DDEF19 = RPB_DDEF19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF20
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_DDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Date getRPB_DDEF20() {
        return RPB_DDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_DDEF20
     *
     * @param RPB_DDEF20 the value for CG.RP_REPORTBEGIN.RPB_DDEF20
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_DDEF20(Date RPB_DDEF20) {
        this.RPB_DDEF20 = RPB_DDEF20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF1
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public Long getRPB_NDEF1() {
        return RPB_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF1
     *
     * @param RPB_NDEF1 the value for CG.RP_REPORTBEGIN.RPB_NDEF1
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF1(Long RPB_NDEF1) {
        this.RPB_NDEF1 = RPB_NDEF1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF2
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF2() {
        return RPB_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF2
     *
     * @param RPB_NDEF2 the value for CG.RP_REPORTBEGIN.RPB_NDEF2
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF2(BigDecimal RPB_NDEF2) {
        this.RPB_NDEF2 = RPB_NDEF2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF3
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF3() {
        return RPB_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF3
     *
     * @param RPB_NDEF3 the value for CG.RP_REPORTBEGIN.RPB_NDEF3
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF3(BigDecimal RPB_NDEF3) {
        this.RPB_NDEF3 = RPB_NDEF3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF4
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF4() {
        return RPB_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF4
     *
     * @param RPB_NDEF4 the value for CG.RP_REPORTBEGIN.RPB_NDEF4
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF4(BigDecimal RPB_NDEF4) {
        this.RPB_NDEF4 = RPB_NDEF4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF5
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF5() {
        return RPB_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF5
     *
     * @param RPB_NDEF5 the value for CG.RP_REPORTBEGIN.RPB_NDEF5
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF5(BigDecimal RPB_NDEF5) {
        this.RPB_NDEF5 = RPB_NDEF5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF6
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF6() {
        return RPB_NDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF6
     *
     * @param RPB_NDEF6 the value for CG.RP_REPORTBEGIN.RPB_NDEF6
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF6(BigDecimal RPB_NDEF6) {
        this.RPB_NDEF6 = RPB_NDEF6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF7
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF7() {
        return RPB_NDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF7
     *
     * @param RPB_NDEF7 the value for CG.RP_REPORTBEGIN.RPB_NDEF7
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF7(BigDecimal RPB_NDEF7) {
        this.RPB_NDEF7 = RPB_NDEF7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF8
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF8() {
        return RPB_NDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF8
     *
     * @param RPB_NDEF8 the value for CG.RP_REPORTBEGIN.RPB_NDEF8
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF8(BigDecimal RPB_NDEF8) {
        this.RPB_NDEF8 = RPB_NDEF8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF9
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF9() {
        return RPB_NDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF9
     *
     * @param RPB_NDEF9 the value for CG.RP_REPORTBEGIN.RPB_NDEF9
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF9(BigDecimal RPB_NDEF9) {
        this.RPB_NDEF9 = RPB_NDEF9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF10
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF10() {
        return RPB_NDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF10
     *
     * @param RPB_NDEF10 the value for CG.RP_REPORTBEGIN.RPB_NDEF10
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF10(BigDecimal RPB_NDEF10) {
        this.RPB_NDEF10 = RPB_NDEF10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF11
     *
     * @return the value of CG.RP_REPORTBEGIN.RPB_NDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public BigDecimal getRPB_NDEF11() {
        return RPB_NDEF11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CG.RP_REPORTBEGIN.RPB_NDEF11
     *
     * @param RPB_NDEF11 the value for CG.RP_REPORTBEGIN.RPB_NDEF11
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void setRPB_NDEF11(BigDecimal RPB_NDEF11) {
        this.RPB_NDEF11 = RPB_NDEF11;
    }

	public String getPageSQLA() {
		return pageSQLA;
	}

	public void setPageSQLA(String pageSQLA) {
		this.pageSQLA = pageSQLA;
	}

	public String getPageSQLB() {
		return pageSQLB;
	}

	public void setPageSQLB(String pageSQLB) {
		this.pageSQLB = pageSQLB;
	}

	public String getSearchA() {
		return searchA;
	}

	public void setSearchA(String searchA) {
		this.searchA = searchA;
	}

	public String getSearchB1() {
		return searchB1;
	}

	public void setSearchB1(String searchB1) {
		this.searchB1 = searchB1;
	}

	public String getSearchB2() {
		return searchB2;
	}

	public void setSearchB2(String searchB2) {
		this.searchB2 = searchB2;
	}

	public String getSearchC() {
		return searchC;
	}

	public void setSearchC(String searchC) {
		this.searchC = searchC;
	}

	public String getSearchD() {
		return searchD;
	}

	public void setSearchD(String searchD) {
		this.searchD = searchD;
	}

	public String getSearchE() {
		return searchE;
	}

	public void setSearchE(String searchE) {
		this.searchE = searchE;
	}

	public String getSearchF() {
		return searchF;
	}

	public void setSearchF(String searchF) {
		this.searchF = searchF;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Override
	public String toString() {
		return "RpReportBeginForm [filePath=" + filePath + ", fileName=" + fileName + ", pageSQLA=" + pageSQLA + ", pageSQLB=" + pageSQLB + ", searchA=" + searchA + ", searchB1=" + searchB1
				+ ", searchB2=" + searchB2 + ", searchC=" + searchC + ", searchD=" + searchD + ", searchE=" + searchE + ", searchF=" + searchF + ", RPB_SNO=" + RPB_SNO + ", RPB_NNUM=" + RPB_NNUM
				+ ", UD_SNO=" + UD_SNO + ", UD_SNO1=" + UD_SNO1 + ", RPB_SREPORTUNITNAME=" + RPB_SREPORTUNITNAME + ", RPB_SPROJECTNAME=" + RPB_SPROJECTNAME + ", RPB_SYEAR=" + RPB_SYEAR + ", EMP_SNO="
				+ EMP_SNO + ", RPB_SPERSON=" + RPB_SPERSON + ", RPB_SPROTYPE=" + RPB_SPROTYPE + ", RPB_SREPORTTOTAL=" + RPB_SREPORTTOTAL + ", RPB_SSUGGESTTOTAL=" + RPB_SSUGGESTTOTAL + ", RPB_SLEVEL="
				+ RPB_SLEVEL + ", RPB_SMEM=" + RPB_SMEM + ", RPB_SISDEL=" + RPB_SISDEL + ", RPB_SISVALID=" + RPB_SISVALID + ", RPB_SREPLYBY=" + RPB_SREPLYBY + ", RPB_SREPLYDATE=" + RPB_SREPLYDATE
				+ ", RPB_SALTERBY=" + RPB_SALTERBY + ", RPB_SALTERDATE=" + RPB_SALTERDATE + ", RPB_SDEF1=" + RPB_SDEF1 + ", RPB_SDEF2=" + RPB_SDEF2 + ", RPB_SDEF3=" + RPB_SDEF3 + ", RPB_SDEF4="
				+ RPB_SDEF4 + ", RPB_SDEF5=" + RPB_SDEF5 + ", RPB_SDEF6=" + RPB_SDEF6 + ", RPB_SDEF7=" + RPB_SDEF7 + ", RPB_SDEF8=" + RPB_SDEF8 + ", RPB_SDEF9=" + RPB_SDEF9 + ", RPB_SDEF10="
				+ RPB_SDEF10 + ", RPB_SDEF11=" + RPB_SDEF11 + ", RPB_SDEF12=" + RPB_SDEF12 + ", RPB_SDEF13=" + RPB_SDEF13 + ", RPB_SDEF14=" + RPB_SDEF14 + ", RPB_SDEF15=" + RPB_SDEF15
				+ ", RPB_DDEF16=" + RPB_DDEF16 + ", RPB_DDEF17=" + RPB_DDEF17 + ", RPB_DDEF18=" + RPB_DDEF18 + ", RPB_DDEF19=" + RPB_DDEF19 + ", RPB_DDEF20=" + RPB_DDEF20 + ", RPB_NDEF1=" + RPB_NDEF1
				+ ", RPB_NDEF2=" + RPB_NDEF2 + ", RPB_NDEF3=" + RPB_NDEF3 + ", RPB_NDEF4=" + RPB_NDEF4 + ", RPB_NDEF5=" + RPB_NDEF5 + ", RPB_NDEF6=" + RPB_NDEF6 + ", RPB_NDEF7=" + RPB_NDEF7
				+ ", RPB_NDEF8=" + RPB_NDEF8 + ", RPB_NDEF9=" + RPB_NDEF9 + ", RPB_NDEF10=" + RPB_NDEF10 + ", RPB_NDEF11=" + RPB_NDEF11 + "]";
	}
	
	
    
    
}