package com.rc.project.dao;

import com.rc.project.form.CkCheckForm;
import com.rc.project.vo.CkCheck;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CkCheckDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public CkCheckDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(String CK_SID) {
        CkCheckForm key = new CkCheckForm();
        key.setCK_SID(CK_SID);
        int rows = getSqlMapClientTemplate().delete("CK_CHECK_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(CkCheckForm record) {
        getSqlMapClientTemplate().insert("CK_CHECK_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(CkCheckForm record) {
        getSqlMapClientTemplate().insert("CK_CHECK_insertSelective", record);
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public CkCheck selectByPrimaryKey(String CK_SID) {
        CkCheckForm key = new CkCheckForm();
        key.setCK_SID(CK_SID);
        CkCheck record = (CkCheck) getSqlMapClientTemplate().queryForObject("CK_CHECK_selectByPrimaryKey", key);
        return record;
    }




    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(CkCheckForm record) {
        int rows = getSqlMapClientTemplate().update("CK_CHECK_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.CK_CHECK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(CkCheckForm record) {
        int rows = getSqlMapClientTemplate().update("CK_CHECK_updateByPrimaryKey", record);
        return rows;
    }


}