package com.rc.project.dao;

import com.rc.project.form.EpAccessoryForm;
import com.rc.project.vo.EpAccessory;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpAccessoryDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpAccessoryDAO() {
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal AS_NID) {
        EpAccessoryForm key = new EpAccessoryForm();
        key.setAS_NID(AS_NID);
        int rows = getSqlMapClientTemplate().delete("EP_ACCESSORY_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpAccessoryForm record) {
    	Object obj = getSqlMapClientTemplate().queryForObject(
				"EP_ACCESSORY_maxid");    	
    	int maxId = obj == null ? 0:(Integer)obj;
    	record.setAS_NID(BigDecimal.valueOf(maxId));
        getSqlMapClientTemplate().insert("EP_ACCESSORY_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpAccessoryForm record) {
        getSqlMapClientTemplate().insert("EP_ACCESSORY_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpAccessory selectByPrimaryKey(BigDecimal AS_NID) {
        EpAccessoryForm key = new EpAccessoryForm();
        key.setAS_NID(AS_NID);
        EpAccessory record = (EpAccessory) getSqlMapClientTemplate().queryForObject("EP_ACCESSORY_selectByPrimaryKey", key);
        return record;
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpAccessoryForm record) {
        int rows = getSqlMapClientTemplate().update("EP_ACCESSORY_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ACCESSORY
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpAccessoryForm record) {
        int rows = getSqlMapClientTemplate().update("EP_ACCESSORY_updateByPrimaryKey", record);
        return rows;
    }

}