package com.rc.project.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.rc.project.form.EpAccessoryForm;
import com.rc.project.form.EpBidForm;
import com.rc.project.form.EpBidWinForm;
import com.rc.project.vo.EpBid;
import com.rc.project.vo.EpBidWin;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpBidWinDAO extends SqlMapClientDaoSupport  {


	public EpBidWin getBidByPackage(String ep_sno,String bg_sno){
    	EpBidWinForm form = new EpBidWinForm();
    	form.setEP_SNO(ep_sno);
    	form.setBG_SNO(bg_sno);
    	return (EpBidWin)getSqlMapClientTemplate().queryForObject("EP_BIDWIN_selectByPackage", form);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal EBW_NID) {
        EpBidWinForm key = new EpBidWinForm();
        key.setEBW_NID(EBW_NID);
        int rows = getSqlMapClientTemplate().delete("EP_BIDWIN_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public boolean insert(EpBidWinForm record) {
        Object o =getSqlMapClientTemplate().insert("EP_BIDWIN_insert", record);
        return o == null ? false:true;
    }
    
    public boolean insert(EpBidWinForm record,EpAccessoryForm fileForm) {
    	if(fileForm == null)return insert(record);
    	boolean result = false;
    	Object obj1 = getSqlMapClientTemplate().queryForObject(
				"EP_BIDWIN_maxid");    	
    	int maxId = obj1 == null ? 0:(Integer)obj1;
    	record.setEBW_NID(BigDecimal.valueOf(maxId));
    	SqlMapClient sqlMapClient = getSqlMapClientTemplate().getSqlMapClient();
    	try {
			sqlMapClient.startTransaction();
			sqlMapClient.startBatch();
			sqlMapClient.insert("EP_BIDWIN_insert", record);
			sqlMapClient.insert("EP_ACCESSORY_insert", fileForm);
			sqlMapClient.executeBatch();
			sqlMapClient.commitTransaction();
			result = true;
		} catch (Exception e) {
			try {
				sqlMapClient.getCurrentConnection().rollback();
			} catch (SQLException e1) {
				e1.printStackTrace();
			}
			e.printStackTrace();
		} finally {
			try {
				sqlMapClient.endTransaction();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
        return result;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpBidWinForm record) {
        getSqlMapClientTemplate().insert("EP_BIDWIN_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpBidWin selectByPrimaryKey(BigDecimal EBW_NID) {
        EpBidWinForm key = new EpBidWinForm();
        key.setEBW_NID(EBW_NID);
        EpBidWin record = (EpBidWin) getSqlMapClientTemplate().queryForObject("EP_BIDWIN_selectByPrimaryKey", key);
        return record;
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpBidWinForm record) {
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpBidWinForm record) {
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByPrimaryKey", record);
        return rows;
    }

}