package com.rc.project.dao;

import com.rc.project.form.EpBidWinForm;
import com.rc.project.vo.EpBidWin;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpBidWinDAO extends SqlMapClientDaoSupport  {



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal EBW_NID) {
        EpBidWinForm key = new EpBidWinForm();
        key.setEBW_NID(EBW_NID);
        int rows = getSqlMapClientTemplate().delete("EP_BIDWIN_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpBidWinForm record) {
        getSqlMapClientTemplate().insert("EP_BIDWIN_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpBidWinForm record) {
        getSqlMapClientTemplate().insert("EP_BIDWIN_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpBidWin selectByPrimaryKey(BigDecimal EBW_NID) {
        EpBidWinForm key = new EpBidWinForm();
        key.setEBW_NID(EBW_NID);
        EpBidWin record = (EpBidWin) getSqlMapClientTemplate().queryForObject("EP_BIDWIN_selectByPrimaryKey", key);
        return record;
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpBidWinForm record) {
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BIDWIN
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpBidWinForm record) {
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByPrimaryKey", record);
        return rows;
    }

}