package com.rc.project.dao;

import com.rc.project.form.EpBidForm;
import com.rc.project.vo.EpBid;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpBidDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpBidDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal EB_NID) {
        EpBidForm key = new EpBidForm();
        key.setEB_NID(EB_NID);
        int rows = getSqlMapClientTemplate().delete("EP_BID_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpBidForm record) {
        getSqlMapClientTemplate().insert("EP_BID_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpBidForm record) {
        getSqlMapClientTemplate().insert("EP_BID_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpBid selectByPrimaryKey(BigDecimal EB_NID) {
        EpBidForm key = new EpBidForm();
        key.setEB_NID(EB_NID);
        EpBid record = (EpBid) getSqlMapClientTemplate().queryForObject("EP_BID_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpBidForm record) {
        int rows = getSqlMapClientTemplate().update("EP_BID_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_BID
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpBidForm record) {
        int rows = getSqlMapClientTemplate().update("EP_BID_updateByPrimaryKey", record);
        return rows;
    }

}