package com.rc.project.dao;

import com.rc.project.form.EpBidWinForm;
import com.rc.project.form.EpContractForm;
import com.rc.project.vo.EpBidWin;
import com.rc.project.vo.EpContract;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpContractDAO extends SqlMapClientDaoSupport{
   
	public EpContract getDetailByPackage(String ep_sno,String bg_sno){
    	EpContractForm form = new EpContractForm();
    	form.setEP_SNO(ep_sno);
    	form.setBG_SNO(bg_sno);
    	return (EpContract)getSqlMapClientTemplate().queryForObject("EP_CONTRACT_selectByPackage", form);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_CONTRACT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(String CT_SNO) {
        EpContractForm key = new EpContractForm();
        key.setCT_SNO(CT_SNO);
        int rows = getSqlMapClientTemplate().delete("EP_CONTRACT_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_CONTRACT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public boolean insert(EpContractForm record) {
        return getSqlMapClientTemplate().insert("EP_CONTRACT_insert", record) == null?false:true;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_CONTRACT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpContractForm record) {
        getSqlMapClientTemplate().insert("EP_CONTRACT_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_CONTRACT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpContract selectByPrimaryKey(String CT_SNO) {
        EpContractForm key = new EpContractForm();
        key.setCT_SNO(CT_SNO);
        EpContract record = (EpContract) getSqlMapClientTemplate().queryForObject("EP_CONTRACT_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_CONTRACT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpContractForm record) {
        int rows = getSqlMapClientTemplate().update("EP_CONTRACT_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_CONTRACT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpContractForm record) {
        int rows = getSqlMapClientTemplate().update("EP_CONTRACT_updateByPrimaryKey", record);
        return rows;
    }

}