package com.rc.project.dao;

import com.rc.project.form.EpEntrancepForm;
import com.rc.project.vo.EpEntrancep;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpEntrancepDAO extends SqlMapClientDaoSupport  {


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ENTRANCEP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(String ETP_SNO) {
        EpEntrancepForm key = new EpEntrancepForm();
        key.setETP_SNO(ETP_SNO);
        int rows = getSqlMapClientTemplate().delete("EP_ENTRANCEP_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ENTRANCEP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpEntrancepForm record) {
        getSqlMapClientTemplate().insert("EP_ENTRANCEP_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ENTRANCEP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpEntrancepForm record) {
        getSqlMapClientTemplate().insert("EP_ENTRANCEP_insertSelective", record);
    }


    
    public EpEntrancep selectByPrimaryKey(String ETP_SNO) {
        EpEntrancepForm key = new EpEntrancepForm();
        key.setETP_SNO(ETP_SNO);
        EpEntrancep record = (EpEntrancep) getSqlMapClientTemplate().queryForObject("EP_ENTRANCEP_selectByPrimaryKey", key);
        return record;
    }
    
    public EpEntrancep selectByEP_SNO(String EP_SNO) {
        EpEntrancepForm key = new EpEntrancepForm();
        key.setEP_SNO(EP_SNO);
        EpEntrancep record = (EpEntrancep) getSqlMapClientTemplate().queryForObject("EP_ENTRANCEP_selectByEP_SNO", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ENTRANCEP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpEntrancepForm record) {
        int rows = getSqlMapClientTemplate().update("EP_ENTRANCEP_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_ENTRANCEP
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpEntrancepForm record) {
        int rows = getSqlMapClientTemplate().update("EP_ENTRANCEP_updateByPrimaryKey", record);
        return rows;
    }
}