package com.rc.project.dao;

import com.rc.project.form.EpFormworkForm;
import com.rc.project.vo.EpFormwork;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpFormworkDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpFormworkDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal FORM_NID) {
        EpFormworkForm key = new EpFormworkForm();
        key.setFORM_NID(FORM_NID);
        int rows = getSqlMapClientTemplate().delete("EP_FORMWORK_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpFormworkForm record) {
        getSqlMapClientTemplate().insert("EP_FORMWORK_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpFormworkForm record) {
        getSqlMapClientTemplate().insert("EP_FORMWORK_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpFormwork selectByPrimaryKey(BigDecimal FORM_NID) {
        EpFormworkForm key = new EpFormworkForm();
        key.setFORM_NID(FORM_NID);
        EpFormwork record = (EpFormwork) getSqlMapClientTemplate().queryForObject("EP_FORMWORK_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpFormworkForm record) {
        int rows = getSqlMapClientTemplate().update("EP_FORMWORK_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_FORMWORK
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpFormworkForm record) {
        int rows = getSqlMapClientTemplate().update("EP_FORMWORK_updateByPrimaryKey", record);
        return rows;
    }

}