package com.rc.project.dao;

import com.rc.project.form.EpMailForm;
import com.rc.project.vo.EpMail;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpMailDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpMailDAO() {
        super();
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal ML_NID) {
        EpMailForm key = new EpMailForm();
        key.setML_NID(ML_NID);
        int rows = getSqlMapClientTemplate().delete("EP_MAIL_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpMailForm record) {
        getSqlMapClientTemplate().insert("EP_MAIL_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpMailForm record) {
        getSqlMapClientTemplate().insert("EP_MAIL_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpMail selectByPrimaryKey(BigDecimal ML_NID) {
        EpMailForm key = new EpMailForm();
        key.setML_NID(ML_NID);
        EpMail record = (EpMail) getSqlMapClientTemplate().queryForObject("EP_MAIL_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpMailForm record) {
        int rows = getSqlMapClientTemplate().update("EP_MAIL_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_MAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpMailForm record) {
        int rows = getSqlMapClientTemplate().update("EP_MAIL_updateByPrimaryKey", record);
        return rows;
    }

}