package com.rc.project.dao;

import com.rc.project.form.EpPackageListForm;
import com.rc.project.vo.EpPackageList;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpPackageListDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpPackageListDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(String EP_SNO) {
        EpPackageListForm key = new EpPackageListForm();
        key.setEP_SNO(EP_SNO);
        int rows = getSqlMapClientTemplate().delete("EP_PACKAGELIST_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpPackageListForm record) {
        getSqlMapClientTemplate().insert("EP_PACKAGELIST_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpPackageListForm record) {
        getSqlMapClientTemplate().insert("EP_PACKAGELIST_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpPackageList selectByPrimaryKey(String EP_SNO) {
        EpPackageListForm key = new EpPackageListForm();
        key.setEP_SNO(EP_SNO);
        EpPackageList record = (EpPackageList) getSqlMapClientTemplate().queryForObject("EP_PACKAGELIST_selectByPrimaryKey", key);
        return record;
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpPackageListForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PACKAGELIST_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PACKAGELIST
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpPackageListForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PACKAGELIST_updateByPrimaryKey", record);
        return rows;
    }
}