package com.rc.project.dao;

import com.rc.project.form.EpPersonForm;
import com.rc.project.vo.EpPerson;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpPersonDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpPersonDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal PER_NID) {
        EpPersonForm key = new EpPersonForm();
        key.setPER_NID(PER_NID);
        int rows = getSqlMapClientTemplate().delete("EP_PERSON_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpPersonForm record) {
        getSqlMapClientTemplate().insert("EP_PERSON_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpPersonForm record) {
        getSqlMapClientTemplate().insert("EP_PERSON_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpPerson selectByPrimaryKey(BigDecimal PER_NID) {
        EpPersonForm key = new EpPersonForm();
        key.setPER_NID(PER_NID);
        EpPerson record = (EpPerson) getSqlMapClientTemplate().queryForObject("EP_PERSON_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpPersonForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PERSON_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PERSON
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpPersonForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PERSON_updateByPrimaryKey", record);
        return rows;
    }

}