package com.rc.project.dao;

import com.rc.project.form.EpProcessForm;
import com.rc.project.vo.EpProcess;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProcessDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpProcessDAO() {
        super();
    }
    
    public List findPage(EpProcessForm form){
    	return getSqlMapClientTemplate().queryForList("EP_PROCESS_findPage", form);
    }
    
    public int findSize(EpProcessForm form){
    	return (Integer)getSqlMapClientTemplate().queryForObject("EP_PROCESS_findSize", form);
    }
    
    public boolean deleteByPackage(String bg_sno){
    	return getSqlMapClientTemplate().delete("EP_PROCESS_deleteByPackage",bg_sno) == 0?false:true;
    }
    


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal SS_NID) {
        EpProcessForm key = new EpProcessForm();
        key.setSS_NID(SS_NID);
        int rows = getSqlMapClientTemplate().delete("EP_PROCESS_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public boolean insert(EpProcessForm record) {
        return getSqlMapClientTemplate().insert("EP_PROCESS_insert", record) == null?false:true;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpProcessForm record) {
        getSqlMapClientTemplate().insert("EP_PROCESS_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpProcess selectByPrimaryKey(BigDecimal SS_NID) {
        EpProcessForm key = new EpProcessForm();
        key.setSS_NID(SS_NID);
        EpProcess record = (EpProcess) getSqlMapClientTemplate().queryForObject("EP_PROCESS_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpProcessForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PROCESS_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROCESS
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public boolean updateByPrimaryKey(EpProcessForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PROCESS_updateByPrimaryKey", record);
        return rows == 0?false:true;
    }

}