package com.rc.project.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.rc.project.form.EpProjectDetailForm;
import com.rc.project.vo.EpProjectDetail;
import com.rc.project.vo.EpProjectDetailExample;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProjectDetailDAO extends SqlMapClientDaoSupport  {

	public List findPage(EpProjectDetailForm form){
    	return getSqlMapClientTemplate().queryForList("EP_PROJECTDETAIL_findPage", form);
    }
    
    public int findSize(EpProjectDetailForm form){
    	return (Integer)getSqlMapClientTemplate().queryForObject("EP_PROJECTDETAIL_findSize", form);
    }
    
    /*
     * 修改采购方式
     * type：修改方式
     * idChecked：明细主键
     */
    public boolean updatePurType(int type,String[] idchecked){
    	boolean bl = false;
		SqlMapClient sqlMapClient = getSqlMapClientTemplate().getSqlMapClient();
		try {
			sqlMapClient.startTransaction();
			sqlMapClient.startBatch();
			if (idchecked != null) {
				for (int i = 0; i < idchecked.length; i++) {
					EpProjectDetailForm form = new EpProjectDetailForm();
					form.setEPD_NID(BigDecimal.valueOf(Integer.valueOf(idchecked[i])));
					form.setEPD_SPURTYPE(String.valueOf(type));
					form.setEPD_SSTAT("2");
					sqlMapClient.update("EP_PROJECTDETAIL_updateByPrimaryKeySelective", form.toVO());
				}
			}
			sqlMapClient.executeBatch();
			sqlMapClient.commitTransaction();
			bl = true;
		} catch (Exception e) {
			try {
				sqlMapClient.getCurrentConnection().rollback();
			} catch (SQLException e1) {
				e1.printStackTrace();
			}
			e.printStackTrace();
		} finally {
			try {
				sqlMapClient.endTransaction();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return bl;
    	/*EpProjectDetailForm form = new EpProjectDetailForm();
		form.setEPD_NID(BigDecimal.valueOf(Integer.valueOf(idchecked[0])));
		form.setEPD_SPURTYPE(String.valueOf(type));
		form.setEPD_SSTAT("2");
		EpProjectDetail vo = form.toVO();
		System.out.println(vo.getEPD_NID());
		System.out.println(vo.getEPD_SPURTYPE());
		System.out.println(vo.getEPD_SSTAT());
    	return getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKeySelective", vo) == 0 ?false:true;*/
    }
    

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int countByExample(EpProjectDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_PROJECTDETAIL_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int deleteByExample(EpProjectDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_PROJECTDETAIL_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int deleteByPrimaryKey(EpProjectDetail key) {
        int rows = getSqlMapClientTemplate().delete("EP_PROJECTDETAIL_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public void insert(EpProjectDetail record) {
        getSqlMapClientTemplate().insert("EP_PROJECTDETAIL_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public void insertSelective(EpProjectDetail record) {
        getSqlMapClientTemplate().insert("EP_PROJECTDETAIL_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public List selectByExample(EpProjectDetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_PROJECTDETAIL_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public EpProjectDetail selectByPrimaryKey(EpProjectDetail key) {
        EpProjectDetail record = (EpProjectDetail) getSqlMapClientTemplate().queryForObject("EP_PROJECTDETAIL_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int updateByExampleSelective(EpProjectDetail record, EpProjectDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int updateByExample(EpProjectDetail record, EpProjectDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int updateByPrimaryKeySelective(EpProjectDetail record) {
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    public int updateByPrimaryKey(EpProjectDetail record) {
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 19 10:36:01 CST 2014
     */
    private static class UpdateByExampleParms extends EpProjectDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpProjectDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}