package com.rc.project.dao;

import com.rc.project.form.EpProjectDetailForm;
import com.rc.project.vo.EpProjectDetail;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProjectDetailDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpProjectDetailDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(EpProjectDetailForm key) {
        int rows = getSqlMapClientTemplate().delete("EP_PROJECTDETAIL_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpProjectDetailForm record) {
        getSqlMapClientTemplate().insert("EP_PROJECTDETAIL_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpProjectDetailForm record) {
        getSqlMapClientTemplate().insert("EP_PROJECTDETAIL_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpProjectDetail selectByPrimaryKey(EpProjectDetailForm key) {
    	EpProjectDetail record = (EpProjectDetail) getSqlMapClientTemplate().queryForObject("EP_PROJECTDETAIL_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpProjectDetailForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_PROJECTDETAIL
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpProjectDetailForm record) {
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKey", record);
        return rows;
    }

}