package com.rc.project.dao;

import com.rc.project.form.EpSettingForm;
import com.rc.project.vo.EpSetting;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpSettingDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpSettingDAO() {
        super();
    }



    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal SET_NID) {
        EpSettingForm key = new EpSettingForm();
        key.setSET_NID(SET_NID);
        int rows = getSqlMapClientTemplate().delete("EP_SETTING_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(EpSettingForm record) {
        getSqlMapClientTemplate().insert("EP_SETTING_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(EpSettingForm record) {
        getSqlMapClientTemplate().insert("EP_SETTING_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public EpSetting selectByPrimaryKey(BigDecimal SET_NID) {
        EpSettingForm key = new EpSettingForm();
        key.setSET_NID(SET_NID);
        EpSetting record = (EpSetting) getSqlMapClientTemplate().queryForObject("EP_SETTING_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(EpSettingForm record) {
        int rows = getSqlMapClientTemplate().update("EP_SETTING_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.EP_SETTING
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(EpSettingForm record) {
        int rows = getSqlMapClientTemplate().update("EP_SETTING_updateByPrimaryKey", record);
        return rows;
    }

}