package com.rc.project.dao;

import com.rc.project.form.RpFileForm;
import com.rc.project.vo.RpFile;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RpFileDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public RpFileDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal RPF_NID) {
        RpFileForm key = new RpFileForm();
        key.setRPF_NID(RPF_NID);
        int rows = getSqlMapClientTemplate().delete("RP_FILE_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(RpFileForm record) {
        getSqlMapClientTemplate().insert("RP_FILE_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(RpFileForm record) {
        getSqlMapClientTemplate().insert("RP_FILE_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public RpFile selectByPrimaryKey(BigDecimal RPF_NID) {
        RpFileForm key = new RpFileForm();
        key.setRPF_NID(RPF_NID);
        RpFile record = (RpFile) getSqlMapClientTemplate().queryForObject("RP_FILE_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(RpFileForm record) {
        int rows = getSqlMapClientTemplate().update("RP_FILE_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_FILE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(RpFileForm record) {
        int rows = getSqlMapClientTemplate().update("RP_FILE_updateByPrimaryKey", record);
        return rows;
    }

}