package com.rc.project.dao;

import com.rc.project.form.RpMiddleForm;
import com.rc.project.vo.RpMiddle;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RpMiddleDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public RpMiddleDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(RpMiddleForm key) {
        int rows = getSqlMapClientTemplate().delete("RP_MIDDLE_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(RpMiddleForm record) {
        getSqlMapClientTemplate().insert("RP_MIDDLE_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(RpMiddleForm record) {
        getSqlMapClientTemplate().insert("RP_MIDDLE_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public RpMiddle selectByPrimaryKey(RpMiddleForm key) {
    	RpMiddle record = (RpMiddle) getSqlMapClientTemplate().queryForObject("RP_MIDDLE_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(RpMiddleForm record) {
        int rows = getSqlMapClientTemplate().update("RP_MIDDLE_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_MIDDLE
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(RpMiddleForm record) {
        int rows = getSqlMapClientTemplate().update("RP_MIDDLE_updateByPrimaryKey", record);
        return rows;
    }

}