package com.rc.project.dao;

import com.rc.project.form.RpReportForm;
import com.rc.project.vo.RpReport;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RpReportDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public RpReportDAO() {
        super();
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int deleteByPrimaryKey(String RP_SNO) {
        RpReportForm key = new RpReportForm();
        key.setRP_SNO(RP_SNO);
        int rows = getSqlMapClientTemplate().delete("RP_REPORT_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insert(RpReportForm record) {
        getSqlMapClientTemplate().insert("RP_REPORT_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public void insertSelective(RpReportForm record) {
        getSqlMapClientTemplate().insert("RP_REPORT_insertSelective", record);
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public RpReport selectByPrimaryKey(String RP_SNO) {
        RpReportForm key = new RpReportForm();
        key.setRP_SNO(RP_SNO);
        RpReport record = (RpReport) getSqlMapClientTemplate().queryForObject("RP_REPORT_selectByPrimaryKey", key);
        return record;
    }


    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKeySelective(RpReportForm record) {
        int rows = getSqlMapClientTemplate().update("RP_REPORT_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CG.RP_REPORT
     *
     * @ibatorgenerated Mon Mar 17 15:29:33 CST 2014
     */
    public int updateByPrimaryKey(RpReportForm record) {
        int rows = getSqlMapClientTemplate().update("RP_REPORT_updateByPrimaryKey", record);
        return rows;
    }
    
    public List selectByPage(RpReportForm record){
    	return getSqlMapClientTemplate().queryForList("RP_REPORT_selectByPage", record);
    }
    
    public int selectByCount(RpReportForm record){
    	return (Integer)getSqlMapClientTemplate().queryForObject("RP_REPORT_selectByCount",record);
    }
    

}